"""Cloudflare-only origin ingress and bounded CrowdSec remediation."""
from __future__ import annotations

import hashlib
import ipaddress
import json
import os
import shlex
import stat
import tempfile
import time
import urllib.error
import urllib.parse
import urllib.request
from contextlib import contextmanager
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Iterable, Iterator, Mapping, Sequence

from . import secrets
from .cli import CommandResult, DoctorCheck, run_command

CLOUDFLARE_IPV4_URL = "https://www.cloudflare.com/ips-v4"
CLOUDFLARE_IPV6_URL = "https://www.cloudflare.com/ips-v6"
CLOUDFLARE_API = "https://api.cloudflare.com/client/v4"
CROWDSEC_REPO_INSTALLER = "https://install.crowdsec.net"
MAX_RESPONSE_BYTES = 64 * 1024
MAX_INSTALLER_BYTES = 512 * 1024
LKG_MAX_AGE_SECONDS = 72 * 60 * 60
CLOCK_SKEW_SECONDS = 5 * 60
CHAIN = "VWOCI-CF-HTTPS"
RULE_COMMENT = "vaultwarden-oci:cloudflare-https"
GUARD_COMMENT = "vaultwarden-oci:cloudflare-guard"
BRIDGE_IFACE = "vwoci0"
BOUNCER_ID = "vaultwarden-oci-cloudflare"
BOUNCER_SERVICE = "crowdsec-cloudflare-worker-bouncer.service"
BOUNCER_BINARY = "/usr/bin/crowdsec-cloudflare-worker-bouncer"
FIREWALL_BOUNCER_ID = "vaultwarden-oci-firewall"
FIREWALL_BOUNCER_SERVICE = "crowdsec-firewall-bouncer.service"
FIREWALL_BOUNCER_BINARY = "crowdsec-firewall-bouncer"
FIREWALL_BOUNCER_CONFIG = Path("/etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml")
FIREWALL_BOUNCER_LOCAL = Path("/etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml.local")
CROWDSEC_SERVICE = "crowdsec.service"
CROWDSEC_COLLECTIONS = (
    "crowdsecurity/caddy",
    "crowdsecurity/linux",
    "crowdsecurity/iptables",
    "Dominic-Wagner/vaultwarden",
)
DEFAULT_LAPI_URL = "http://127.0.0.1:8080"
POLICY_RC_D = Path("/usr/sbin/policy-rc.d")
CSCLI_SETUP_MARKER = '# Configuration generated by "cscli setup".'
CSCLI_CHECKSUM_PREFIX = "# cscli-checksum: "
STATE_ROOT = Path("/var/lib/vaultwarden-oci/state")
LKG_PATH = STATE_ROOT / "cloudflare-ranges.json"
CADDY_LOG = Path("/var/lib/vaultwarden-oci/caddy/log/access.log")
VAULTWARDEN_LOG = Path("/var/lib/vaultwarden-oci/vaultwarden/log/vaultwarden.log")
VAULTWARDEN_LOGROTATE = Path("/etc/logrotate.d/vaultwarden-oci-vaultwarden")
CROWDSEC_ACQUIS_MAIN = Path("/etc/crowdsec/acquis.yaml")
ACQUIS_PATH = Path("/etc/crowdsec/acquis.d/vaultwarden-oci.yaml")
BOUNCER_DROPIN = Path(
    "/etc/systemd/system/crowdsec-cloudflare-worker-bouncer.service.d/vaultwarden-oci.conf"
)
RUNTIME_CONFIG = Path("/run/vaultwarden-oci/transient/crowdsec-cloudflare-worker-bouncer.yaml")
REMEDIATION_START_TOKEN = Path("/run/vaultwarden-oci/transient/crowdsec-cloudflare-start.token")
FAIL_OPEN_CONFIRMATION = STATE_ROOT / "crowdsec-cloudflare-fail-open.json"
CADDYFILE = Path("/run/vaultwarden-oci/transient/Caddyfile")
CADDY_CONTAINER = "vaultwarden-oci-caddy"
ADMIN_TOKEN_FILE = Path("/run/vaultwarden-oci/secrets/vaultwarden/vaultwarden_admin_token")
ADMIN_HASH_FILE = Path("/run/vaultwarden-oci/secrets/caddy/admin_basic_auth_hash")

Runner = Callable[..., CommandResult]
Fetcher = Callable[[str, int], str]


class EdgeError(RuntimeError):
    """Raised when no safe supported edge policy can be established."""


@dataclass(frozen=True)
class CloudflarePolicy:
    ipv4: tuple[ipaddress.IPv4Network, ...]
    ipv6: tuple[ipaddress.IPv6Network, ...]
    fetched_at: int
    source: str

    @property
    def cidrs(self) -> tuple[str, ...]:
        return tuple(str(network) for network in (*self.ipv4, *self.ipv6))


@dataclass(frozen=True)
class EdgePaths:
    lkg: Path = LKG_PATH
    acquisition: Path = ACQUIS_PATH
    bouncer_dropin: Path = BOUNCER_DROPIN
    remediation_config: Path = RUNTIME_CONFIG
    caddy_log: Path = CADDY_LOG
    remediation_start_token: Path = REMEDIATION_START_TOKEN
    fail_open_confirmation: Path = FAIL_OPEN_CONFIRMATION


def _safe_network(network: ipaddress._BaseNetwork) -> bool:
    return not (
        network.is_private
        or network.is_loopback
        or network.is_link_local
        or network.is_multicast
        or network.is_reserved
        or network.is_unspecified
    )


def parse_cidrs(text: str, family: int) -> tuple[ipaddress._BaseNetwork, ...]:
    """Strictly parse one canonical public Cloudflare CIDR per line."""
    if family not in {4, 6}:
        raise ValueError(family)
    if not isinstance(text, str) or not text or "\x00" in text:
        raise EdgeError(f"Cloudflare IPv{family} response is empty or invalid")
    networks: list[ipaddress._BaseNetwork] = []
    seen: set[str] = set()
    for raw in text.splitlines():
        if not raw or raw != raw.strip() or raw.startswith("#"):
            raise EdgeError(f"Cloudflare IPv{family} response contains a malformed line")
        try:
            network = ipaddress.ip_network(raw, strict=True)
        except ValueError as exc:
            raise EdgeError(f"Cloudflare IPv{family} response contains an invalid CIDR") from exc
        if network.version != family or not _safe_network(network):
            raise EdgeError(f"Cloudflare IPv{family} response contains an unsafe CIDR")
        canonical = str(network)
        if canonical in seen:
            raise EdgeError(f"Cloudflare IPv{family} response contains duplicate CIDRs")
        seen.add(canonical)
        networks.append(network)
    minimum = 2 if family == 4 else 1
    if not minimum <= len(networks) <= 64:
        raise EdgeError(f"Cloudflare IPv{family} response has an implausible CIDR count")
    ordered = sorted(networks, key=lambda item: (int(item.network_address), item.prefixlen))
    for left, right in zip(ordered, ordered[1:]):
        if left.overlaps(right):
            raise EdgeError(f"Cloudflare IPv{family} response contains overlapping CIDRs")
    return tuple(ordered)


def validate_policy(ipv4_text: str, ipv6_text: str, *, fetched_at: int, source: str) -> CloudflarePolicy:
    return CloudflarePolicy(
        ipv4=tuple(parse_cidrs(ipv4_text, 4)),
        ipv6=tuple(parse_cidrs(ipv6_text, 6)),
        fetched_at=fetched_at,
        source=source,
    )


def _http_text(url: str, maximum: int = MAX_RESPONSE_BYTES) -> str:
    request = urllib.request.Request(
        url,
        headers={"User-Agent": "VaultWarden-OCI cloudflare-edge-policy"},
        method="GET",
    )
    try:
        with urllib.request.urlopen(request, timeout=10) as response:
            if response.status != 200:
                raise EdgeError(f"HTTPS fetch failed with status {response.status}")
            body = response.read(maximum + 1)
    except (OSError, urllib.error.URLError, urllib.error.HTTPError) as exc:
        raise EdgeError("HTTPS fetch failed") from exc
    if len(body) > maximum:
        raise EdgeError("HTTPS response exceeds the allowed size")
    try:
        return body.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise EdgeError("HTTPS response is not UTF-8") from exc


def fetch_cloudflare_policy(*, now: int | None = None, fetcher: Fetcher = _http_text) -> CloudflarePolicy:
    timestamp = int(time.time()) if now is None else int(now)
    return validate_policy(
        fetcher(CLOUDFLARE_IPV4_URL, MAX_RESPONSE_BYTES),
        fetcher(CLOUDFLARE_IPV6_URL, MAX_RESPONSE_BYTES),
        fetched_at=timestamp,
        source="current",
    )


def _atomic_write(path: Path, text: str, mode: int = 0o600) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.parent / f".{path.name}.{os.getpid()}.tmp"
    fd = os.open(
        tmp,
        os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, "O_NOFOLLOW", 0),
        mode,
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(text)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(tmp, path)
        os.chmod(path, mode)
    except Exception:
        tmp.unlink(missing_ok=True)
        raise


def persist_lkg(policy: CloudflarePolicy, path: Path = LKG_PATH) -> None:
    payload = {
        "schema_version": 1,
        "fetched_at": policy.fetched_at,
        "ipv4": [str(item) for item in policy.ipv4],
        "ipv6": [str(item) for item in policy.ipv6],
    }
    try:
        _atomic_write(path, json.dumps(payload, sort_keys=True, separators=(",", ":")) + "\n")
    except OSError as exc:
        raise EdgeError(f"cannot persist Cloudflare last-known-good policy: {exc}") from exc


def load_lkg(path: Path = LKG_PATH, *, now: int | None = None) -> CloudflarePolicy:
    timestamp = int(time.time()) if now is None else int(now)
    try:
        info = path.lstat()
        if stat.S_ISLNK(info.st_mode) or not stat.S_ISREG(info.st_mode):
            raise EdgeError("Cloudflare last-known-good path is not a regular file")
        payload = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise EdgeError("no Cloudflare last-known-good policy exists") from exc
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise EdgeError("Cloudflare last-known-good policy is unreadable") from exc
    if not isinstance(payload, dict) or payload.get("schema_version") != 1:
        raise EdgeError("Cloudflare last-known-good policy schema is invalid")
    fetched_at = payload.get("fetched_at")
    ipv4 = payload.get("ipv4")
    ipv6 = payload.get("ipv6")
    if (
        not isinstance(fetched_at, int)
        or isinstance(fetched_at, bool)
        or not isinstance(ipv4, list)
        or not all(isinstance(item, str) for item in ipv4)
        or not isinstance(ipv6, list)
        or not all(isinstance(item, str) for item in ipv6)
    ):
        raise EdgeError("Cloudflare last-known-good policy fields are invalid")
    age = timestamp - fetched_at
    if age < -CLOCK_SKEW_SECONDS:
        raise EdgeError("Cloudflare last-known-good policy timestamp is in the future")
    if age > LKG_MAX_AGE_SECONDS:
        raise EdgeError("Cloudflare last-known-good policy is stale")
    return validate_policy(
        "\n".join(ipv4),
        "\n".join(ipv6),
        fetched_at=fetched_at,
        source="last-known-good",
    )


def select_policy(
    *,
    path: Path = LKG_PATH,
    now: int | None = None,
    fetcher: Fetcher = _http_text,
) -> CloudflarePolicy:
    timestamp = int(time.time()) if now is None else int(now)
    try:
        policy = fetch_cloudflare_policy(now=timestamp, fetcher=fetcher)
        persist_lkg(policy, path)
        return policy
    except EdgeError as current_error:
        try:
            return load_lkg(path, now=timestamp)
        except EdgeError as cached_error:
            raise EdgeError(
                f"no safe Cloudflare CIDR policy exists: current fetch invalid; {cached_error}"
            ) from current_error


def _command(
    runner: Runner,
    argv: Sequence[str],
    label: str,
    *,
    env: Mapping[str, str] | None = None,
) -> None:
    result = runner(argv, env=env) if env is not None else runner(argv)
    if not result.ok:
        detail = result.kind if result.returncode is None else f"exit {result.returncode}"
        raise EdgeError(f"{label} failed ({detail})")


def _apt_command(
    runner: Runner,
    argv: Sequence[str],
    label: str,
    *,
    env: Mapping[str, str] | None = None,
) -> None:
    result = runner(argv, env=env) if env is not None else runner(argv)
    if result.ok:
        return
    code = result.kind if result.returncode is None else f"exit {result.returncode}"
    raw = "\n".join(part.strip() for part in (result.stderr, result.stdout) if part.strip())
    lines = [line.strip() for line in raw.splitlines() if line.strip()]
    tail = " | ".join(lines[-8:])
    if len(tail) > 1200:
        tail = tail[-1200:]
    detail = tail or "no package-manager diagnostic output; inspect /var/log/apt/term.log"
    raise EdgeError(f"{label} failed ({code}): {detail}")


def _rule(binary: str, comment: str, target: str) -> list[str]:
    return [
        binary,
        "-w",
        "-p",
        "tcp",
        "-o",
        BRIDGE_IFACE,
        "-m",
        "conntrack",
        "--ctdir",
        "ORIGINAL",
        "--ctorigdstport",
        "443",
        "-m",
        "comment",
        "--comment",
        comment,
        "-j",
        target,
    ]


def _ensure_guard(binary: str, runner: Runner) -> None:
    _command(runner, [binary, "-w", "-n", "-L", "DOCKER-USER"], f"{binary} Docker hook check")
    guard = _rule(binary, GUARD_COMMENT, "DROP")
    if not runner([binary, "-w", "-C", "DOCKER-USER", *guard[2:]]).ok:
        _command(
            runner,
            [binary, "-w", "-I", "DOCKER-USER", "1", *guard[2:]],
            f"{binary} fail-closed guard install",
        )


def install_fail_closed_guard(*, runner: Runner = run_command) -> None:
    errors: list[str] = []
    for binary in ("iptables", "ip6tables"):
        try:
            _ensure_guard(binary, runner)
        except EdgeError as exc:
            errors.append(str(exc))
    if errors:
        raise EdgeError("; ".join(errors))


def _rebuild_family(
    binary: str,
    networks: Iterable[ipaddress._BaseNetwork],
    runner: Runner,
) -> None:
    if not runner([binary, "-w", "-n", "-L", CHAIN]).ok:
        _command(runner, [binary, "-w", "-N", CHAIN], f"{binary} chain creation")
    _command(runner, [binary, "-w", "-F", CHAIN], f"{binary} chain flush")
    for network in networks:
        _command(
            runner,
            [binary, "-w", "-A", CHAIN, "-s", str(network), "-j", "RETURN"],
            f"{binary} Cloudflare allow rule",
        )
    _command(runner, [binary, "-w", "-A", CHAIN, "-j", "DROP"], f"{binary} default deny rule")

    jump = _rule(binary, RULE_COMMENT, CHAIN)
    while runner([binary, "-w", "-C", "DOCKER-USER", *jump[2:]]).ok:
        _command(
            runner,
            [binary, "-w", "-D", "DOCKER-USER", *jump[2:]],
            f"{binary} stale edge jump removal",
        )
    _command(
        runner,
        [binary, "-w", "-I", "DOCKER-USER", "2", *jump[2:]],
        f"{binary} edge jump install",
    )
    guard = _rule(binary, GUARD_COMMENT, "DROP")
    _command(
        runner,
        [binary, "-w", "-D", "DOCKER-USER", *guard[2:]],
        f"{binary} fail-closed guard removal",
    )


def apply_origin_policy(policy: CloudflarePolicy, *, runner: Runner = run_command) -> None:
    """Apply both families while a scoped top-of-chain guard blocks published 443 ingress."""
    install_fail_closed_guard(runner=runner)
    _rebuild_family("iptables", policy.ipv4, runner)
    _rebuild_family("ip6tables", policy.ipv6, runner)


def refresh_origin_policy(
    *,
    path: Path = LKG_PATH,
    now: int | None = None,
    fetcher: Fetcher = _http_text,
    runner: Runner = run_command,
) -> CloudflarePolicy:
    install_fail_closed_guard(runner=runner)
    policy = select_policy(path=path, now=now, fetcher=fetcher)
    apply_origin_policy(policy, runner=runner)
    return policy


def _write_root_file(path: Path, content: str, mode: int) -> None:
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        _atomic_write(path, content, mode)
    except OSError as exc:
        raise EdgeError(f"cannot write {path}: {exc}") from exc


def _managed_path(paths: EdgePaths, production: Path, test_name: str) -> Path:
    return production if paths == EdgePaths() else paths.acquisition.parent / test_name


def _vaultwarden_log_path(paths: EdgePaths) -> Path:
    return _managed_path(paths, VAULTWARDEN_LOG, "vaultwarden.log")


def _firewall_config_path(paths: EdgePaths) -> Path:
    return _managed_path(paths, FIREWALL_BOUNCER_CONFIG, "crowdsec-firewall-bouncer.yaml")


def _firewall_local_path(paths: EdgePaths) -> Path:
    return _managed_path(paths, FIREWALL_BOUNCER_LOCAL, "crowdsec-firewall-bouncer.yaml.local")


def _logrotate_path(paths: EdgePaths) -> Path:
    return _managed_path(paths, VAULTWARDEN_LOGROTATE, "vaultwarden-logrotate")


def _prepare_vaultwarden_log(path: Path) -> None:
    if path == VAULTWARDEN_LOG:
        from .runtime import VAULTWARDEN_GID, VAULTWARDEN_UID
        uid, gid = VAULTWARDEN_UID, VAULTWARDEN_GID
    else:
        uid, gid = os.geteuid(), os.getegid()
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        os.chown(path.parent, uid, gid)
        os.chmod(path.parent, 0o700)
        descriptor = os.open(
            path,
            os.O_WRONLY | os.O_CREAT | os.O_APPEND | getattr(os, "O_NOFOLLOW", 0),
            0o600,
        )
        os.close(descriptor)
        os.chown(path, uid, gid)
        os.chmod(path, 0o600)
        info = path.lstat()
    except OSError as exc:
        raise EdgeError(f"cannot prepare Vaultwarden CrowdSec log {path}: {exc}") from exc
    if stat.S_ISLNK(info.st_mode) or not stat.S_ISREG(info.st_mode):
        raise EdgeError(f"Vaultwarden CrowdSec log is not a regular file: {path}")


def acquisition_text(
    caddy_log: Path = CADDY_LOG,
    vaultwarden_log: Path = VAULTWARDEN_LOG,
) -> str:
    return f'''# Managed by VaultWarden-OCI. One appliance-owned CrowdSec acquisition file.
source: file
filenames:
  - {vaultwarden_log}
force_inotify: true
labels:
  type: Vaultwarden

---
source: file
filenames:
  - {caddy_log}
force_inotify: true
labels:
  type: caddy

---
source: journalctl
journalctl_filter:
  - "_SYSTEMD_UNIT=ssh.service"
labels:
  type: syslog

---
source: journalctl
journalctl_filter:
  - "_TRANSPORT=kernel"
labels:
  type: syslog
'''


def firewall_bouncer_bootstrap_local_text() -> str:
    """Install the INPUT-only invariant before package maintainer scripts can run."""
    return '''# Managed by VaultWarden-OCI. Safety override written before package configuration.
mode: nftables
disable_ipv4: false
disable_ipv6: false
nftables:
  ipv4:
    enabled: true
    set-only: false
    table: crowdsec
    chain: crowdsec-chain
    priority: -10
  ipv6:
    enabled: true
    set-only: false
    table: crowdsec6
    chain: crowdsec6-chain
    priority: -10
nftables_hooks:
  - input
'''


def firewall_bouncer_local_text(*, api_key: str, lapi_url: str) -> str:
    """Restrict the firewall bouncer to host INPUT with a project-owned LAPI key."""
    q = json.dumps
    return f'''# Managed by VaultWarden-OCI. Merged over the package-owned base config.
mode: nftables
api_url: {q(lapi_url)}
api_key: {q(api_key)}
origins: []
disable_ipv4: false
disable_ipv6: false
deny_action: DROP
supported_decisions_types:
  - ban
nftables:
  ipv4:
    enabled: true
    set-only: false
    table: crowdsec
    chain: crowdsec-chain
    priority: -10
  ipv6:
    enabled: true
    set-only: false
    table: crowdsec6
    chain: crowdsec6-chain
    priority: -10
nftables_hooks:
  - input
prometheus:
  enabled: false
  listen_addr: 127.0.0.1
  listen_port: 60601
'''


def vaultwarden_logrotate_text(path: Path = VAULTWARDEN_LOG) -> str:
    return f'''{path} {{
    daily
    rotate 7
    maxsize 10M
    missingok
    notifempty
    compress
    delaycompress
    copytruncate
}}
'''


def bouncer_dropin_text(config: Path = RUNTIME_CONFIG) -> str:
    return f'''# Managed by VaultWarden-OCI.
[Service]
Restart=no
ExecCondition=
ExecCondition=/usr/local/bin/vwctl crowdsec consume-start-token
ExecStart=
ExecStartPre=
ExecStartPre=/usr/local/bin/vwctl crowdsec prepare-remediation
ExecStartPre={BOUNCER_BINARY} -c {config} -t
ExecStart={BOUNCER_BINARY} -c {config}
'''


def _download_installer() -> Path:
    text = _http_text(CROWDSEC_REPO_INSTALLER, MAX_INSTALLER_BYTES)
    runtime = Path("/run/vaultwarden-oci/transient")
    runtime.mkdir(parents=True, exist_ok=True)
    descriptor, name = tempfile.mkstemp(prefix="crowdsec-repo-", suffix=".sh", dir=runtime)
    path = Path(name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(text)
            handle.flush()
            os.fsync(handle.fileno())
        os.chmod(path, 0o700)
        return path
    except Exception:
        path.unlink(missing_ok=True)
        raise


def _has_noncomment_content(path: Path) -> bool:
    try:
        text = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return False
    except (OSError, UnicodeError) as exc:
        raise EdgeError(f"cannot inspect CrowdSec acquisition {path}: {exc}") from exc
    return any(line.strip() and not line.lstrip().startswith("#") for line in text.splitlines())


def _is_cscli_setup_acquisition(path: Path) -> bool:
    if not path.name.startswith("setup.") or path.suffix.lower() not in {".yaml", ".yml"}:
        return False
    try:
        info = path.lstat()
        if not stat.S_ISREG(info.st_mode):
            return False
        lines = path.read_text(encoding="utf-8").splitlines()
    except FileNotFoundError:
        return False
    except (OSError, UnicodeError) as exc:
        raise EdgeError(f"cannot inspect CrowdSec generated acquisition {path}: {exc}") from exc

    header: list[str] = []
    checksums: list[str] = []
    content_start: int | None = None
    for index, line in enumerate(lines):
        if not line.startswith("#") and line.strip():
            content_start = index
            break
        header.append(line)
        if line.startswith(CSCLI_CHECKSUM_PREFIX):
            checksums.append(line[len(CSCLI_CHECKSUM_PREFIX):].strip())

    if CSCLI_SETUP_MARKER not in header or len(checksums) != 1:
        return False
    checksum = checksums[0]
    if (
        len(checksum) != 32
        or any(char not in "0123456789abcdef" for char in checksum)
        or content_start is None
    ):
        return False

    # Match CrowdSec clisetup.VerifyChecksum: the generated header is excluded,
    # the remaining lines are normalized to LF, and the declared value must be
    # a prefix of the SHA-256 digest of that exact remainder.
    content = ("\n".join(lines[content_start:]) + "\n").encode("utf-8")
    return hashlib.sha256(content).hexdigest().startswith(checksum)


def _remove_cscli_setup_acquisitions(paths: EdgePaths) -> None:
    directory = paths.acquisition.parent
    try:
        entries = sorted(directory.iterdir(), key=lambda entry: entry.name)
    except FileNotFoundError:
        return
    except OSError as exc:
        raise EdgeError(f"cannot inspect CrowdSec acquisition directory {directory}: {exc}") from exc
    for entry in entries:
        if entry == paths.acquisition or not _is_cscli_setup_acquisition(entry):
            continue
        try:
            entry.unlink()
        except OSError as exc:
            raise EdgeError(f"cannot remove CrowdSec cscli-generated acquisition {entry}: {exc}") from exc


def _assert_acquisition_scope(paths: EdgePaths) -> None:
    directory = paths.acquisition.parent
    try:
        candidates = sorted(
            (entry for entry in directory.iterdir() if entry.suffix.lower() in {".yaml", ".yml"}),
            key=lambda entry: entry.name,
        )
    except FileNotFoundError:
        directory.mkdir(parents=True, exist_ok=True)
        candidates = []
    except OSError as exc:
        raise EdgeError(f"cannot inspect CrowdSec acquisition directory {directory}: {exc}") from exc
    unexpected = [entry for entry in candidates if entry != paths.acquisition]
    if unexpected:
        names = ", ".join(entry.name for entry in unexpected)
        raise EdgeError(f"unexpected CrowdSec acquisition file(s): {names}")
    if paths == EdgePaths() and _has_noncomment_content(CROWDSEC_ACQUIS_MAIN):
        raise EdgeError(
            "unexpected active CrowdSec /etc/crowdsec/acquis.yaml; "
            "VaultWarden-OCI requires one project-managed acquisition file"
        )


def _unlink_state(path: Path, label: str) -> None:
    try:
        path.unlink(missing_ok=True)
    except OSError as exc:
        raise EdgeError(f"cannot clear {label}: {exc}") from exc


@contextmanager
def _suppress_package_service_starts(path: Path) -> Iterator[None]:
    flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, "O_NOFOLLOW", 0)
    try:
        descriptor = os.open(path, flags, 0o755)
    except FileExistsError as exc:
        raise EdgeError(
            f"cannot safely suppress CrowdSec package service auto-start because {path} already exists; "
            "preserve the host policy and resolve it explicitly before retrying"
        ) from exc
    except OSError as exc:
        raise EdgeError(f"cannot create temporary package service policy {path}: {exc}") from exc
    identity = os.fstat(descriptor)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
            handle.write("#!/bin/sh\nexit 101\n")
            handle.flush()
            os.fsync(handle.fileno())
        os.chmod(path, 0o755)
        yield
    finally:
        try:
            current = path.lstat()
        except FileNotFoundError:
            current = None
        except OSError as exc:
            raise EdgeError(f"cannot inspect temporary package service policy {path}: {exc}") from exc
        if current is not None:
            if (current.st_dev, current.st_ino) != (identity.st_dev, identity.st_ino):
                raise EdgeError(
                    f"temporary package service policy {path} changed unexpectedly; refusing to remove it"
                )
            try:
                path.unlink()
            except OSError as exc:
                raise EdgeError(f"cannot remove temporary package service policy {path}: {exc}") from exc


def _package_install_env() -> dict[str, str]:
    """Build the isolated apt environment used for CrowdSec packages only."""
    install_env = dict(os.environ)
    install_env["DEBIAN_FRONTEND"] = "noninteractive"
    install_env["CROWDSEC_SETUP_UNATTENDED_DISABLE"] = "1"
    # Current CrowdSec and firewall-bouncer Debian maintainer scripts call
    # systemctl directly. SYSTEMD_OFFLINE makes start/restart no-ops for this
    # child transaction without contaminating later project-owned systemctl.
    install_env["SYSTEMD_OFFLINE"] = "1"
    return install_env


def _service_absent(result: CommandResult) -> bool:
    detail = (result.stdout + "\n" + result.stderr).lower()
    return any(
        marker in detail
        for marker in (
            "does not exist",
            "could not be found",
            "not loaded",
            "no such file",
            "unit file not found",
        )
    )


def _contain_package_bouncers(runner: Runner) -> list[str]:
    """Disable/stop package-owned services before project configuration begins."""
    problems: list[str] = []
    for service, label in (
        (CROWDSEC_SERVICE, "CrowdSec engine"),
        (BOUNCER_SERVICE, "Cloudflare bouncer"),
        (FIREWALL_BOUNCER_SERVICE, "firewall bouncer"),
    ):
        result = runner(["systemctl", "disable", "--now", service])
        if result.ok or _service_absent(result):
            continue
        detail = result.kind if result.returncode is None else f"exit {result.returncode}"
        problems.append(f"{label} disable/stop could not be proven ({detail})")
    return problems


def _parse_hook_list(text: str) -> tuple[str, ...] | None:
    lines = text.splitlines()
    for index, raw in enumerate(lines):
        stripped = raw.strip()
        if not stripped.startswith("nftables_hooks:"):
            continue
        tail = stripped.split(":", 1)[1].strip()
        if tail:
            if not (tail.startswith("[") and tail.endswith("]")):
                return None
            inner = tail[1:-1].strip()
            if not inner:
                return ()
            return tuple(item.strip().strip("\"'") for item in inner.split(","))
        hooks: list[str] = []
        for following in lines[index + 1:]:
            item = following.strip()
            if not item or item.startswith("#"):
                continue
            if not item.startswith("-"):
                break
            value = item[1:].strip().strip("\"'")
            if not value:
                return None
            hooks.append(value)
        return tuple(hooks)
    return None


def _effective_firewall_hooks(paths: EdgePaths, runner: Runner) -> tuple[str, ...] | None:
    result = runner(
        [FIREWALL_BOUNCER_BINARY, "-c", str(_firewall_config_path(paths)), "-T"]
    )
    if not result.ok:
        return None
    return _parse_hook_list(result.stdout)


def _firewall_config_input_only(paths: EdgePaths, runner: Runner) -> bool:
    """Check the merged hook policy without initializing the nftables backend."""
    return _effective_firewall_hooks(paths, runner) == ("input",)


def _nft_table_input_only(
    runner: Runner,
    *,
    family: str,
    table: str,
    chain_base: str,
) -> bool:
    result = runner(["nft", "--json", "list", "table", family, table])
    if not result.ok:
        return False
    try:
        payload = json.loads(result.stdout)
    except (json.JSONDecodeError, TypeError):
        return False
    entries = payload.get("nftables") if isinstance(payload, dict) else None
    if not isinstance(entries, list):
        return False
    hooked_chains: list[tuple[str, str]] = []
    for entry in entries:
        if not isinstance(entry, dict):
            continue
        chain = entry.get("chain")
        if not isinstance(chain, dict):
            continue
        if chain.get("family") != family or chain.get("table") != table:
            continue
        hook = chain.get("hook")
        if hook is None:
            continue
        name = chain.get("name")
        if not isinstance(name, str) or not isinstance(hook, str):
            return False
        hooked_chains.append((name, hook))
    return sorted(hooked_chains) == [(f"{chain_base}-input", "input")]


def _live_firewall_input_only(runner: Runner) -> bool:
    return _nft_table_input_only(
        runner,
        family="ip",
        table="crowdsec",
        chain_base="crowdsec-chain",
    ) and _nft_table_input_only(
        runner,
        family="ip6",
        table="crowdsec6",
        chain_base="crowdsec6-chain",
    )


def _firewall_boundary_healthy(
    paths: EdgePaths,
    runner: Runner,
    *,
    require_live: bool,
) -> bool:
    # firewall-bouncer v0.0.36 initializes its backend before handling -t and
    # tears that backend down on exit. Keep -t strictly pre-start; live proof
    # must be observational so health/doctor checks cannot remove nftables state.
    if not require_live:
        config = _firewall_config_path(paths)
        if not runner([FIREWALL_BOUNCER_BINARY, "-c", str(config), "-t"]).ok:
            return False
    if not _firewall_config_input_only(paths, runner):
        return False
    return not require_live or _live_firewall_input_only(runner)


def _create_lapi_bouncer_key(runner: Runner, bouncer_id: str, label: str) -> str:
    runner(["cscli", "bouncers", "delete", bouncer_id, "--ignore-missing"])
    created = runner(["cscli", "-oraw", "bouncers", "add", bouncer_id])
    key = created.stdout.strip() if created.ok else ""
    if not key or any(char.isspace() for char in key):
        raise EdgeError(f"cannot create CrowdSec LAPI credential for {label}")
    return key


def _local_lapi_url(runner: Runner) -> str:
    result = runner(["cscli", "config", "show", "-oraw", "--key", "Config.API.Server.ListenURI"])
    raw = result.stdout.strip() if result.ok else ""
    if not raw:
        return DEFAULT_LAPI_URL
    if raw.startswith(":"):
        raw = "127.0.0.1" + raw
    candidate = raw if "://" in raw else "http://" + raw
    parsed = urllib.parse.urlparse(candidate)
    try:
        port = parsed.port
    except ValueError as exc:
        raise EdgeError("CrowdSec local API listen address is invalid") from exc
    if (
        parsed.scheme not in {"http", "https"}
        or parsed.hostname not in {"127.0.0.1", "localhost", "::1"}
        or port is None
        or not 1 <= port <= 65535
        or parsed.username is not None
        or parsed.password is not None
        or parsed.path not in {"", "/"}
        or parsed.params
        or parsed.query
        or parsed.fragment
    ):
        raise EdgeError("CrowdSec local API must listen on a local loopback address")
    host = f"[{parsed.hostname}]" if parsed.hostname == "::1" else parsed.hostname
    return f"{parsed.scheme}://{host}:{port}"


def setup_crowdsec(
    *,
    paths: EdgePaths = EdgePaths(),
    runner: Runner = run_command,
    policy_path: Path | None = None,
) -> None:
    if os.geteuid() != 0 and paths == EdgePaths():
        raise EdgeError("vwctl crowdsec setup must run as root")
    installer: Path | None = None
    try:
        installer = _download_installer()
        _command(runner, ["/bin/sh", str(installer)], "CrowdSec repository setup")
    finally:
        if installer is not None:
            installer.unlink(missing_ok=True)
    _command(runner, ["apt-get", "update"], "apt metadata refresh")
    install_env = _package_install_env()
    if policy_path is None:
        policy_path = POLICY_RC_D if paths == EdgePaths() else paths.acquisition.parent / ".policy-rc.d"

    # The firewall-bouncer package ships INPUT+FORWARD defaults and package
    # scripts call systemctl directly. Establish the INPUT-only merge override
    # before apt and keep SYSTEMD_OFFLINE scoped to the apt child so neither
    # CrowdSec nor either bouncer can actually start during package configure.
    _write_root_file(
        _firewall_local_path(paths),
        firewall_bouncer_bootstrap_local_text(),
        0o600,
    )

    install_error: EdgeError | None = None
    try:
        with _suppress_package_service_starts(policy_path):
            _apt_command(
                runner,
                [
                    "apt-get",
                    "install",
                    "-y",
                    "crowdsec",
                    "crowdsec-cloudflare-worker-bouncer",
                    "crowdsec-firewall-bouncer-nftables",
                    "logrotate",
                ],
                "CrowdSec package installation",
                env=install_env,
            )
    except EdgeError as exc:
        install_error = exc

    containment_errors = _contain_package_bouncers(runner)
    if install_error is not None:
        if containment_errors:
            raise EdgeError(
                f"{install_error}; package service containment also failed: "
                + "; ".join(containment_errors)
            ) from install_error
        raise install_error
    if containment_errors:
        raise EdgeError("package service containment failed: " + "; ".join(containment_errors))

    _command(runner, ["systemctl", "stop", CROWDSEC_SERVICE], "CrowdSec stop before source restriction")
    _command(runner, ["cscli", "collections", "remove", "--all"], "CrowdSec collection reset")
    _remove_cscli_setup_acquisitions(paths)
    _assert_acquisition_scope(paths)
    _command(runner, ["cscli", "hub", "update"], "CrowdSec Hub metadata refresh")
    for collection in CROWDSEC_COLLECTIONS:
        _command(
            runner,
            ["cscli", "collections", "install", collection],
            f"CrowdSec collection installation ({collection})",
        )
    vaultwarden_log = _vaultwarden_log_path(paths)
    _prepare_vaultwarden_log(vaultwarden_log)
    _write_root_file(
        paths.acquisition,
        acquisition_text(paths.caddy_log, vaultwarden_log),
        0o600,
    )
    _write_root_file(_logrotate_path(paths), vaultwarden_logrotate_text(vaultwarden_log), 0o644)
    _write_root_file(paths.bouncer_dropin, bouncer_dropin_text(paths.remediation_config), 0o644)
    _unlink_state(paths.remediation_start_token, "CrowdSec remediation start token")
    _unlink_state(paths.fail_open_confirmation, "CrowdSec Fail Open confirmation")
    _command(runner, ["systemctl", "daemon-reload"], "systemd reload")
    _command(runner, ["systemctl", "enable", "--now", CROWDSEC_SERVICE], "CrowdSec enable/start")
    _command(runner, ["systemctl", "restart", CROWDSEC_SERVICE], "CrowdSec restart")
    firewall_key = _create_lapi_bouncer_key(runner, FIREWALL_BOUNCER_ID, "host firewall remediation")
    _write_root_file(
        _firewall_local_path(paths),
        firewall_bouncer_local_text(api_key=firewall_key, lapi_url=_local_lapi_url(runner)),
        0o600,
    )
    if not _firewall_boundary_healthy(paths, runner, require_live=False):
        raise EdgeError(
            "CrowdSec firewall bouncer effective configuration is not valid INPUT-only nftables policy"
        )
    _command(
        runner,
        ["systemctl", "enable", "--now", FIREWALL_BOUNCER_SERVICE],
        "CrowdSec firewall bouncer enable/start",
    )
    if not _firewall_boundary_healthy(paths, runner, require_live=True):
        containment = _contain_package_bouncers(runner)
        suffix = f"; disable/stop also failed: {'; '.join(containment)}" if containment else ""
        raise EdgeError(
            "CrowdSec firewall bouncer live nftables ownership is not exactly host INPUT"
            + suffix
        )


def crowdsec_decisions(*, runner: Runner = run_command) -> CommandResult:
    """List decisions through the existing CrowdSec authority."""
    return runner(["cscli", "decisions", "list"])


def crowdsec_unban(value: str, *, runner: Runner = run_command) -> str:
    """Remove decisions for one validated address under the global mutation lock."""
    try:
        address = str(ipaddress.ip_address(value))
    except ValueError as exc:
        raise EdgeError(f"invalid IP address {value!r}") from exc
    if os.geteuid() != 0:
        raise EdgeError("vwctl crowdsec unban must run as root")
    from .cli import mutation_lock

    with mutation_lock():
        _command(runner, ["cscli", "decisions", "delete", "--ip", address], "CrowdSec decision removal")
    return address


def _cloudflare_json(url: str, token: str) -> Mapping[str, object]:
    request = urllib.request.Request(
        url,
        headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/json",
            "User-Agent": "VaultWarden-OCI crowdsec-cloudflare",
        },
        method="GET",
    )
    try:
        with urllib.request.urlopen(request, timeout=10) as response:
            raw = response.read(MAX_RESPONSE_BYTES + 1)
            if response.status != 200 or len(raw) > MAX_RESPONSE_BYTES:
                raise EdgeError("Cloudflare API request failed")
    except (OSError, urllib.error.URLError, urllib.error.HTTPError) as exc:
        raise EdgeError("Cloudflare API request failed") from exc
    try:
        payload = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise EdgeError("Cloudflare API returned invalid JSON") from exc
    if not isinstance(payload, dict) or payload.get("success") is not True:
        raise EdgeError("Cloudflare API rejected the remediation credential")
    return payload


def resolve_cloudflare_zone(domain: str, token: str) -> tuple[str, str]:
    labels = domain.rstrip(".").lower().split(".")
    if len(labels) < 2:
        raise EdgeError("site domain is not a valid Cloudflare hostname")
    for index in range(0, len(labels) - 1):
        candidate = ".".join(labels[index:])
        query = urllib.parse.urlencode({"name": candidate, "status": "active", "per_page": "1"})
        payload = _cloudflare_json(f"{CLOUDFLARE_API}/zones?{query}", token)
        result = payload.get("result")
        if not isinstance(result, list) or not result:
            continue
        zone = result[0]
        if not isinstance(zone, dict) or zone.get("name") != candidate:
            continue
        zone_id = zone.get("id")
        account = zone.get("account")
        account_id = account.get("id") if isinstance(account, dict) else None
        if isinstance(zone_id, str) and zone_id and isinstance(account_id, str) and account_id:
            return account_id, zone_id
    raise EdgeError("Cloudflare remediation token cannot resolve the configured site zone")


def remediation_config_text(
    *,
    lapi_key: str,
    token: str,
    account_id: str,
    zone_id: str,
    domain: str,
    lapi_url: str = DEFAULT_LAPI_URL,
) -> str:
    q = json.dumps
    return f'''crowdsec_config:
  lapi_key: {q(lapi_key)}
  lapi_url: {q(lapi_url)}
  update_frequency: 10s
  include_scenarios_containing: []
  exclude_scenarios_containing: []
  only_include_decisions_from: ["cscli", "crowdsec"]
  insecure_skip_verify: false
  key_path: ""
  cert_path: ""
  ca_cert_path: ""
cloudflare_config:
  accounts:
    - id: {q(account_id)}
      zones:
        - zone_id: {q(zone_id)}
          actions:
            - ban
          default_action: ban
          routes_to_protect:
            - {q(domain + "/*")}
          turnstile:
            enabled: false
            rotate_secret_key: false
            rotate_secret_key_every: 168h0m0s
            mode: managed
      token: {q(token)}
      account_name: "vaultwarden-oci"
log_level: info
log_media: "stdout"
log_dir: "/var/log/"
ban_template_path: ""
prometheus:
  enabled: false
  listen_addr: 127.0.0.1
  listen_port: "2112"
'''


def prepare_remediation(
    *,
    config_path: Path,
    secret_paths: secrets.SecretPaths = secrets.SecretPaths(),
    output: Path = RUNTIME_CONFIG,
    runner: Runner = run_command,
) -> None:
    from .runtime import RuntimeConfigError, load_config

    try:
        config = load_config(config_path)
    except RuntimeConfigError as exc:
        raise EdgeError(str(exc)) from exc
    values = secrets.load(
        config.offline_recovery_recipient,
        paths=secret_paths,
        runner=runner,
        uid=0 if output == RUNTIME_CONFIG else os.geteuid(),
    )
    token = values.get("cloudflare_remediation_token")
    if not token:
        raise EdgeError("SOPS secrets require cloudflare_remediation_token for CrowdSec Cloudflare remediation")
    lapi_key = _create_lapi_bouncer_key(runner, BOUNCER_ID, "Cloudflare remediation")
    account_id, zone_id = resolve_cloudflare_zone(config.domain, token)
    lapi_url = _local_lapi_url(runner)
    try:
        _atomic_write(
            output,
            remediation_config_text(
                lapi_key=lapi_key,
                token=token,
                account_id=account_id,
                zone_id=zone_id,
                domain=config.domain,
                lapi_url=lapi_url,
            ),
            0o600,
        )
    except OSError as exc:
        raise EdgeError(f"cannot materialize CrowdSec Cloudflare remediation config: {exc}") from exc


def _active(service: str, runner: Runner) -> bool:
    return runner(["systemctl", "is-active", "--quiet", service]).ok


def _enabled(service: str, runner: Runner) -> bool:
    return runner(["systemctl", "is-enabled", "--quiet", service]).ok


def _disabled(service: str, runner: Runner) -> bool:
    result = runner(["systemctl", "is-enabled", service])
    return result.stdout.strip() == "disabled"


def consume_remediation_start_token(*, path: Path = REMEDIATION_START_TOKEN) -> None:
    try:
        info = path.lstat()
    except FileNotFoundError as exc:
        raise EdgeError("CrowdSec Cloudflare remediation start was not authorized by vwctl") from exc
    except OSError as exc:
        raise EdgeError(f"cannot inspect CrowdSec remediation start token: {exc}") from exc
    if stat.S_ISLNK(info.st_mode) or not stat.S_ISREG(info.st_mode):
        raise EdgeError("CrowdSec Cloudflare remediation start token is not a regular file")
    try:
        path.unlink()
    except OSError as exc:
        raise EdgeError(f"cannot consume CrowdSec remediation start token: {exc}") from exc


def start_remediation(*, paths: EdgePaths = EdgePaths(), runner: Runner = run_command) -> None:
    if os.geteuid() != 0 and paths == EdgePaths():
        raise EdgeError("vwctl crowdsec remediation-start must run as root")
    if _active(BOUNCER_SERVICE, runner):
        raise EdgeError("CrowdSec Cloudflare remediation is already active")
    if not _disabled(BOUNCER_SERVICE, runner):
        raise EdgeError("CrowdSec Cloudflare bouncer must remain disabled at boot; rerun vwctl crowdsec setup")
    _unlink_state(paths.fail_open_confirmation, "CrowdSec Fail Open confirmation")
    try:
        _atomic_write(paths.remediation_start_token, f"{os.getpid()}:{time.time_ns()}\n", 0o600)
    except OSError as exc:
        raise EdgeError(f"cannot authorize CrowdSec remediation start: {exc}") from exc
    result = runner(["systemctl", "start", BOUNCER_SERVICE])
    if not result.ok or not _active(BOUNCER_SERVICE, runner) or paths.remediation_start_token.exists():
        _unlink_state(paths.remediation_start_token, "CrowdSec remediation start token")
        detail = result.kind if result.returncode is None else f"exit {result.returncode}"
        raise EdgeError(f"CrowdSec Cloudflare remediation start failed ({detail})")

    # The start owner also owns proof of what this exact process invocation
    # loaded. A config file that merely looks correct after start is not enough.
    from . import crowdsec_worker_policy

    try:
        crowdsec_worker_policy.attest_current(paths, runner)
    except crowdsec_worker_policy.WorkerPolicyError as exc:
        stopped = runner(["systemctl", "stop", BOUNCER_SERVICE])
        suffix = "" if stopped.ok and not _active(BOUNCER_SERVICE, runner) else "; unproven Worker stop could not be proven"
        raise EdgeError(
            f"CrowdSec Cloudflare remediation started but local-only decision policy could not be proven: {exc}{suffix}"
        ) from exc


def _service_invocation_id(runner: Runner) -> str | None:
    if not _active(BOUNCER_SERVICE, runner):
        return None
    result = runner(["systemctl", "show", BOUNCER_SERVICE, "--property=InvocationID", "--value"])
    value = result.stdout.strip().lower() if result.ok else ""
    if len(value) != 32 or any(char not in "0123456789abcdef" for char in value):
        return None
    return value


def confirm_fail_open(
    *,
    paths: EdgePaths = EdgePaths(),
    runner: Runner = run_command,
    now: int | None = None,
) -> None:
    if os.geteuid() != 0 and paths == EdgePaths():
        raise EdgeError("vwctl crowdsec confirm-fail-open must run as root")
    invocation = _service_invocation_id(runner)
    if invocation is None:
        raise EdgeError("CrowdSec Cloudflare remediation is not active with a valid systemd invocation")
    payload = {
        "schema_version": 1,
        "invocation_id": invocation,
        "confirmed_at": int(time.time()) if now is None else int(now),
    }
    try:
        _atomic_write(
            paths.fail_open_confirmation,
            json.dumps(payload, sort_keys=True, separators=(",", ":")) + "\n",
            0o600,
        )
    except OSError as exc:
        raise EdgeError(f"cannot persist CrowdSec Fail Open confirmation: {exc}") from exc


def _fail_open_confirmed(path: Path, invocation: str | None) -> bool:
    if invocation is None:
        return False
    try:
        info = path.lstat()
        if stat.S_ISLNK(info.st_mode) or not stat.S_ISREG(info.st_mode):
            return False
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (FileNotFoundError, OSError, UnicodeError, json.JSONDecodeError):
        return False
    return (
        isinstance(payload, dict)
        and payload.get("schema_version") == 1
        and payload.get("invocation_id") == invocation
        and isinstance(payload.get("confirmed_at"), int)
        and not isinstance(payload.get("confirmed_at"), bool)
    )


def _iptables_healthy(binary: str, networks: Iterable[ipaddress._BaseNetwork], runner: Runner) -> bool:
    jump = _rule(binary, RULE_COMMENT, CHAIN)
    guard = _rule(binary, GUARD_COMMENT, "DROP")
    if not runner([binary, "-w", "-C", "DOCKER-USER", *jump[2:]]).ok:
        return False
    if runner([binary, "-w", "-C", "DOCKER-USER", *guard[2:]]).ok:
        return False
    listing = runner([binary, "-w", "-S", CHAIN])
    if not listing.ok:
        return False
    expected = [
        ("-A", CHAIN, "-s", str(network), "-j", "RETURN")
        for network in networks
    ]
    expected.append(("-A", CHAIN, "-j", "DROP"))
    try:
        actual = [tuple(shlex.split(line)) for line in listing.stdout.splitlines() if line.startswith(f"-A {CHAIN} ")]
    except ValueError:
        return False
    return actual == expected


def _caddy_trust_configured(caddy_text: str) -> bool:
    return (
        "trusted_proxies cloudflare {" in caddy_text
        and "timeout 15s" in caddy_text
        and "trusted_proxies_strict" in caddy_text
        and "client_ip_headers CF-Connecting-IP" in caddy_text
        and "trusted_proxies static" not in caddy_text
    )


def _caddy_admin_disabled(caddy_text: str) -> bool:
    return "@admin path /admin*" in caddy_text and "respond @admin 404" in caddy_text


def _caddy_admin_protected(caddy_text: str) -> bool:
    if "@admin path /admin*" not in caddy_text:
        return False
    start = caddy_text.find(" handle @admin {")
    if start < 0:
        return False
    end = caddy_text.find(" @auth path", start)
    if end < 0:
        return False
    admin_block = caddy_text[start:end]
    return all(
        marker in admin_block
        for marker in (
            "rate_limit {",
            "zone admin {",
            "key {client_ip}",
            "basic_auth {",
            "admin {env.ADMIN_BASIC_AUTH_HASH}",
        )
    )


def doctor_checks(
    *,
    paths: EdgePaths = EdgePaths(),
    runner: Runner = run_command,
    now: int | None = None,
) -> list[DoctorCheck]:
    checks: list[DoctorCheck] = []
    try:
        caddy_text = CADDYFILE.read_text(encoding="utf-8")
    except (OSError, UnicodeError):
        checks.append(DoctorCheck("edge.caddy.trusted_proxy", "SKIP", "rendered Caddy config is not present; service may be stopped"))
        checks.append(DoctorCheck("edge.admin.protection", "SKIP", "rendered Caddy admin policy is not present; service may be stopped"))
    else:
        trusted = _caddy_trust_configured(caddy_text)
        checks.append(DoctorCheck(
            "edge.caddy.trusted_proxy",
            "PASS" if trusted else "FAIL",
            "Caddy uses strict Cloudflare trusted proxies with a bounded refresh and CF-Connecting-IP" if trusted
            else "Caddy trusted-proxy strictness/timeout/CF-Connecting-IP configuration is missing or duplicated with static CIDRs",
        ))
        admin_disabled = _caddy_admin_disabled(caddy_text)
        admin_gated = _caddy_admin_protected(caddy_text)
        if admin_disabled:
            checks.append(DoctorCheck("edge.admin.protection", "PASS", "Vaultwarden admin route is disabled at Caddy"))
        elif admin_gated and ADMIN_TOKEN_FILE.exists() and ADMIN_HASH_FILE.exists():
            checks.append(DoctorCheck("edge.admin.protection", "PASS", "admin token capability, per-client rate limit, and outer Basic Auth gate are active"))
        else:
            checks.append(DoctorCheck("edge.admin.protection", "FAIL", "admin route is missing Vaultwarden token capability, rate limit, or outer Basic Auth gate"))

    caddy_state = runner(["docker", "container", "inspect", "--format", "{{json .State}}", CADDY_CONTAINER])
    healthy = False
    if caddy_state.ok:
        try:
            state = json.loads(caddy_state.stdout)
            healthy = isinstance(state, dict) and state.get("Status") == "running" and (
                not isinstance(state.get("Health"), dict) or state["Health"].get("Status") == "healthy"
            )
        except (json.JSONDecodeError, TypeError, AttributeError):
            healthy = False
    caddy_absent = (not caddy_state.ok) and "no such" in (caddy_state.stderr + caddy_state.stdout).lower()
    checks.append(DoctorCheck(
        "edge.caddy.health",
        "PASS" if healthy else "SKIP" if caddy_absent else "FAIL",
        "Caddy container is running and healthy" if healthy
        else "Caddy container is not present; service may be stopped" if caddy_absent
        else "Caddy container is stopped, unhealthy, or could not be inspected",
    ))
    policy: CloudflarePolicy | None = None
    try:
        policy = load_lkg(paths.lkg, now=now)
    except EdgeError as exc:
        checks.append(DoctorCheck("edge.cloudflare.cidrs", "FAIL", str(exc)))
    else:
        age = (int(time.time()) if now is None else int(now)) - policy.fetched_at
        checks.append(DoctorCheck("edge.cloudflare.cidrs", "PASS", f"validated Cloudflare last-known-good policy age={max(0, age)}s"))
    if policy is not None and _iptables_healthy("iptables", policy.ipv4, runner) and _iptables_healthy("ip6tables", policy.ipv6, runner):
        checks.append(DoctorCheck("edge.cloudflare.iptables", "PASS", f"Cloudflare-only ORIGINAL-direction Docker 443 policy is complete on {BRIDGE_IFACE}"))
    else:
        checks.append(DoctorCheck("edge.cloudflare.iptables", "FAIL", "Cloudflare Docker 443 policy is missing, guarded, stale, misdirected, or has unexpected rules"))

    if _active(CROWDSEC_SERVICE, runner):
        checks.append(DoctorCheck("crowdsec.engine", "PASS", "CrowdSec Security Engine is active"))
    else:
        checks.append(DoctorCheck("crowdsec.engine", "FAIL", "CrowdSec Security Engine is not active"))

    installed_collections = all(
        runner(["cscli", "collections", "inspect", collection]).ok
        for collection in CROWDSEC_COLLECTIONS
    )
    checks.append(DoctorCheck(
        "crowdsec.hub",
        "PASS" if installed_collections else "FAIL",
        "Caddy, Linux/SSH, iptables/kernel, and Vaultwarden detection collections are installed"
        if installed_collections
        else "required CrowdSec detection collections are incomplete",
    ))

    firewall_bouncer = runner(["cscli", "bouncers", "inspect", FIREWALL_BOUNCER_ID, "-o", "json"])
    firewall_ok = (
        _active(FIREWALL_BOUNCER_SERVICE, runner)
        and _enabled(FIREWALL_BOUNCER_SERVICE, runner)
        and firewall_bouncer.ok
        and _firewall_boundary_healthy(paths, runner, require_live=True)
    )
    checks.append(DoctorCheck(
        "crowdsec.firewall",
        "PASS" if firewall_ok else "FAIL",
        "CrowdSec firewall bouncer effective config and live nftables ownership are host INPUT only"
        if firewall_ok
        else "CrowdSec host-input firewall remediation service/LAPI/effective-config/live-nftables state is unhealthy or not INPUT-only",
    ))

    active = _active(BOUNCER_SERVICE, runner)
    disabled = _disabled(BOUNCER_SERVICE, runner)
    config_test = runner([BOUNCER_BINARY, "-c", str(paths.remediation_config), "-t"])
    bouncer = runner(["cscli", "bouncers", "inspect", BOUNCER_ID, "-o", "json"])
    invocation = _service_invocation_id(runner) if active else None
    confirmed = _fail_open_confirmed(paths.fail_open_confirmation, invocation)
    if active and disabled and config_test.ok and bouncer.ok and confirmed:
        checks.append(DoctorCheck("crowdsec.cloudflare", "PASS", "Cloudflare Worker bouncer is active, boot-disabled, and Fail Open is operator-confirmed for this invocation"))
    elif active and disabled and config_test.ok and bouncer.ok:
        checks.append(DoctorCheck("crowdsec.cloudflare", "FAIL", "Cloudflare Worker bouncer is active but Fail Open is not confirmed for this service invocation"))
    else:
        checks.append(DoctorCheck("crowdsec.cloudflare", "FAIL", "CrowdSec Cloudflare remediation service/config/LAPI state is unhealthy or not explicitly armed"))

    # Keep the source-policy proof in the canonical doctor owner so direct
    # callers and every presentation layer see the same result.
    from . import crowdsec_worker_policy

    return crowdsec_worker_policy.enforce_doctor_checks(
        checks,
        paths=paths,
        runner=runner,
    )
