#!/usr/bin/env bash
# cron-setup.sh - Setup automated maintenance tasks for VaultWarden-OCI-NG

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$SCRIPT_DIR"
cd "$PROJECT_ROOT"

source "lib/common.sh"
init_common_lib "$0"

# Configuration
CRON_FILE="/tmp/vaultwarden-cron"
INSTALL_CRON=false
REMOVE_CRON=false
DRY_RUN=false

show_help() {
    cat << 'EOF'
VaultWarden-OCI-NG Cron Setup

USAGE:
    ./cron-setup.sh [OPTIONS]

OPTIONS:
    --install       Install cron jobs
    --remove        Remove cron jobs
    --dry-run       Show what would be done without executing
    --help          Show this help

EXAMPLES:
    ./cron-setup.sh --install       # Install automated maintenance tasks
    ./cron-setup.sh --remove        # Remove all cron jobs
    ./cron-setup.sh --dry-run       # Preview cron jobs without installing

AUTOMATED TASKS:
    - Cloudflare IP updates (weekly)
    - System health checks (daily)
    - Log rotation (daily)
    - Docker cleanup (weekly)
    - Backup creation (daily at 2 AM)
EOF
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --install) INSTALL_CRON=true; shift ;;
        --remove) REMOVE_CRON=true; shift ;;
        --dry-run) DRY_RUN=true; shift ;;
        --help) show_help; exit 0 ;;
        *) log_error "Unknown option: $1"; show_help; exit 1 ;;
    esac
done

# Validate arguments
if [[ "$INSTALL_CRON" == "false" && "$REMOVE_CRON" == "false" ]]; then
    log_error "Either --install or --remove must be specified"
    show_help
    exit 1
fi

if [[ "$INSTALL_CRON" == "true" && "$REMOVE_CRON" == "true" ]]; then
    log_error "Cannot specify both --install and --remove"
    exit 1
fi

create_cron_jobs() {
    log_info "Creating cron jobs configuration..."
    
    # Clear the temp file
    > "$CRON_FILE"
    
    # Add header
    cat >> "$CRON_FILE" << EOF
# VaultWarden-OCI-NG Automated Maintenance Tasks
# Generated by cron-setup.sh on $(date)
# Project location: $PROJECT_ROOT

# Set PATH for cron environment
PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin

EOF

    # Daily backup at 2:00 AM
    echo "# Daily backup creation (2:00 AM)" >> "$CRON_FILE"
    echo "0 2 * * * cd $PROJECT_ROOT && ./backup.sh --create --quiet >/dev/null 2>&1" >> "$CRON_FILE"
    echo "" >> "$CRON_FILE"

    # Weekly Cloudflare IP update (Sundays at 3:00 AM)
    echo "# Weekly Cloudflare IP update (Sundays, 3:00 AM)" >> "$CRON_FILE"
    echo "0 3 * * 0 cd $PROJECT_ROOT && ./update-cloudflare-ips.sh >/dev/null 2>&1" >> "$CRON_FILE"
    echo "" >> "$CRON_FILE"

    # Daily health check (6:00 AM)
    echo "# Daily system health check (6:00 AM)" >> "$CRON_FILE"
    echo "0 6 * * * cd $PROJECT_ROOT && ./health.sh --comprehensive --quiet >/dev/null 2>&1" >> "$CRON_FILE"
    echo "" >> "$CRON_FILE"

    # Weekly Docker cleanup (Sundays at 4:00 AM)
    echo "# Weekly Docker system cleanup (Sundays, 4:00 AM)" >> "$CRON_FILE"
    echo "0 4 * * 0 cd $PROJECT_ROOT && make cleanup >/dev/null 2>&1" >> "$CRON_FILE"
    echo "" >> "$CRON_FILE"

    # Daily log rotation check (1:00 AM)
    echo "# Daily log rotation check (1:00 AM)" >> "$CRON_FILE"
    echo "0 1 * * * cd $PROJECT_ROOT && find ${PROJECT_STATE_DIR:-/var/lib/vaultwarden}/logs -name '*.log' -size +100M -exec truncate -s 50M {} \; 2>/dev/null" >> "$CRON_FILE"
    echo "" >> "$CRON_FILE"

    # Monthly container image update (1st of month, 5:00 AM)
    echo "# Monthly container image update (1st of month, 5:00 AM)" >> "$CRON_FILE"
    echo "0 5 1 * * cd $PROJECT_ROOT && make update >/dev/null 2>&1" >> "$CRON_FILE"
    echo "" >> "$CRON_FILE"

    # Weekly certificate renewal check (Sundays at 2:30 AM)
    echo "# Weekly SSL certificate renewal check (Sundays, 2:30 AM)" >> "$CRON_FILE"
    echo "30 2 * * 0 cd $PROJECT_ROOT && docker compose exec caddy caddy reload --config /etc/caddy/Caddyfile >/dev/null 2>&1" >> "$CRON_FILE"
    echo "" >> "$CRON_FILE"

    log_success "Cron jobs configuration created"
}

install_cron_jobs() {
    if [[ "$DRY_RUN" == "true" ]]; then
        log_info "[DRY RUN] Would install the following cron jobs:"
        cat "$CRON_FILE"
        return 0
    fi

    log_info "Installing cron jobs..."
    
    # Backup existing crontab
    local backup_file="/tmp/vaultwarden-cron-backup-$(date +%Y%m%d-%H%M%S)"
    if crontab -l > "$backup_file" 2>/dev/null; then
        log_info "Existing crontab backed up to: $backup_file"
    else
        log_info "No existing crontab found"
    fi
    
    # Get current crontab and append our jobs
    (crontab -l 2>/dev/null || true; cat "$CRON_FILE") | crontab -
    
    log_success "Cron jobs installed successfully"
    log_info "View installed jobs with: crontab -l"
    
    # Cleanup temp file
    rm -f "$CRON_FILE"
}

remove_cron_jobs() {
    if [[ "$DRY_RUN" == "true" ]]; then
        log_info "[DRY RUN] Would remove VaultWarden-OCI-NG cron jobs"
        log_info "Current crontab entries that would be removed:"
        crontab -l 2>/dev/null | grep -E "(VaultWarden-OCI-NG|$PROJECT_ROOT)" || log_info "No matching cron jobs found"
        return 0
    fi

    log_info "Removing VaultWarden-OCI-NG cron jobs..."
    
    # Backup current crontab
    local backup_file="/tmp/vaultwarden-cron-backup-$(date +%Y%m%d-%H%M%S)"
    if crontab -l > "$backup_file" 2>/dev/null; then
        log_info "Current crontab backed up to: $backup_file"
        
        # Remove lines containing our project path or identifier
        crontab -l 2>/dev/null | grep -v -E "(VaultWarden-OCI-NG|$PROJECT_ROOT)" | crontab -
        
        log_success "VaultWarden-OCI-NG cron jobs removed"
        log_info "Backup of previous crontab: $backup_file"
    else
        log_info "No existing crontab found"
    fi
}

validate_environment() {
    log_info "Validating environment for cron setup..."
    
    # Check if required scripts exist
    local required_scripts=("backup.sh" "health.sh" "update-cloudflare-ips.sh")
    local missing_scripts=()
    
    for script in "${required_scripts[@]}"; do
        if [[ ! -f "$PROJECT_ROOT/$script" ]]; then
            missing_scripts+=("$script")
        fi
    done
    
    if [[ ${#missing_scripts[@]} -gt 0 ]]; then
        log_warn "Missing scripts: ${missing_scripts[*]}"
        log_info "Some cron jobs may fail until these scripts are available"
    fi
    
    # Check if make command exists
    if ! has_command make; then
        log_warn "make command not found - some maintenance tasks will fail"
    fi
    
    # Check PROJECT_STATE_DIR
    if [[ ! -d "${PROJECT_STATE_DIR:-/var/lib/vaultwarden}" ]]; then
        log_warn "Project state directory not found: ${PROJECT_STATE_DIR:-/var/lib/vaultwarden}"
        log_info "This may cause log rotation tasks to fail"
    fi
    
    log_success "Environment validation completed"
}

main() {
    log_info "VaultWarden-OCI-NG Cron Setup"
    
    if [[ "$DRY_RUN" == "true" ]]; then
        log_warn "DRY RUN MODE - No changes will be made"
    fi
    
    validate_environment
    
    if [[ "$INSTALL_CRON" == "true" ]]; then
        create_cron_jobs
        install_cron_jobs
        
        log_success "Cron setup completed successfully"
        echo ""
        echo "Installed automated tasks:"
        echo "  • Daily backups at 2:00 AM"
        echo "  • Weekly Cloudflare IP updates (Sundays, 3:00 AM)"
        echo "  • Daily health checks at 6:00 AM"
        echo "  • Weekly Docker cleanup (Sundays, 4:00 AM)"
        echo "  • Daily log rotation at 1:00 AM"
        echo "  • Monthly image updates (1st of month, 5:00 AM)"
        echo "  • Weekly certificate checks (Sundays, 2:30 AM)"
        echo ""
        echo "Management commands:"
        echo "  View jobs:   crontab -l"
        echo "  Remove jobs: ./cron-setup.sh --remove"
        
    elif [[ "$REMOVE_CRON" == "true" ]]; then
        remove_cron_jobs
        log_success "Cron removal completed successfully"
    fi
}

main "$@"
