#!/usr/bin/env bash
# cron-setup.sh - Setup automated maintenance tasks for VaultWarden-OCI-NG
# Modernized for new backup, maintenance, and update scripts.
# UPDATED: Added dynamic DNS updates and Cloudflare IP range updates for security

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$SCRIPT_DIR"
cd "$PROJECT_ROOT"

source "lib/common.sh"
init_common_lib "$0"

# Configuration
CRON_FILE="/tmp/vaultwarden-cron-$(id -u)"
INSTALL_CRON=false
REMOVE_CRON=false
DRY_RUN=false

show_help() {
    cat << 'EOF'
VaultWarden-OCI-NG Cron Setup (Enhanced with Security Automation)

USAGE:
    sudo ./cron-setup.sh [OPTIONS]

OPTIONS:
    --install       Install cron jobs for the current user
    --remove        Remove cron jobs for the current user
    --dry-run       Show what would be done without executing
    --help          Show this help

EXAMPLES:
    sudo ./cron-setup.sh --install       # Install automated maintenance tasks
    sudo ./cron-setup.sh --remove        # Remove all cron jobs
    sudo ./cron-setup.sh --dry-run       # Preview cron jobs without installing

AUTOMATED TASKS:
    - Every 15min: Dynamic DNS Updates (replaces ddclient)
    - Weekly: Cloudflare IP Range Updates (UFW security sync)
    - Daily DB Backups (with rclone sync)
    - Weekly Full Backups (with rclone sync)
    - Daily Health Checks (with email alerts)
    - Weekly Maintenance (Docker prune, backup cleanup)
    - Weekly System (OS) Package Updates
    - Quarterly Database Maintenance (VACUUM)
EOF
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --install) INSTALL_CRON=true; shift ;;
        --remove) REMOVE_CRON=true; shift ;;
        --dry-run) DRY_RUN=true; shift ;;
        --help) show_help; exit 0 ;;
        *) log_error "Unknown option: $1"; show_help; exit 1 ;;
    esac
done

# Validate arguments
if [[ "$INSTALL_CRON" == "false" && "$REMOVE_CRON" == "false" ]]; then
    log_error "Either --install or --remove must be specified"
    show_help
    exit 1
fi

if [[ "$INSTALL_CRON" == "true" && "$REMOVE_CRON" == "true" ]]; then
    log_error "Cannot specify both --install and --remove"
    exit 1
fi

if ! is_root; then
    log_error "This script must be run with sudo to install cron jobs."
    exit 1
fi

create_cron_jobs() {
    log_info "Creating cron jobs configuration with security automation..."

    local real_user; real_user=$(get_real_user)

    # Clear the temp file
    > "$CRON_FILE"

    # Add header
    cat >> "$CRON_FILE" << EOF
# VaultWarden-OCI-NG Automated Maintenance Tasks
# Generated by cron-setup.sh on $(date)
# Project location: $PROJECT_ROOT
# DO NOT EDIT THIS FILE MANUALLY - Use ./cron-setup.sh

# Set PATH for cron environment
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Run all commands as the project user
SHELL=/bin/bash
USER=$real_user

# Wrapper function to log cron job output
log_job() {
    local job_name="\$1"
    shift
    local cmd="\$@"
    local log_dir="$PROJECT_ROOT/logs"
    local log_file="\$log_dir/cron-jobs.log"
    mkdir -p "\$log_dir"
    echo "[\$(date -uIs)] [Cron Job: \$job_name] START" >> "\$log_file"
    if ! \$cmd >> "\$log_file" 2>&1; then
        echo "[\$(date -uIs)] [Cron Job: \$job_name] FAILED with exit code \$?" >> "\$log_file"
    else
        echo "[\$(date -uIs)] [Cron Job: \$job_name] SUCCESS" >> "\$log_file"
    fi
}
export -f log_job

# --- Cron Jobs ---

# Dynamic DNS Updates (every 15 minutes) - Replaces ddclient
*/15 * * * * cd $PROJECT_ROOT && log_job "DNS Update" ./update-dns.sh

# Cloudflare IP Range Updates (Sundays at 3:00 AM) - NEW: Security sync
0 3 * * 0 cd $PROJECT_ROOT && log_job "CF IP Update" sudo ./maintenance.sh --type cf-ranges

# Daily DB Backup (2:00 AM)
0 2 * * * cd $PROJECT_ROOT && log_job "DB Backup" ./backup.sh --type db --rclone

# Weekly Full Backup (Sunday 4:00 AM)
0 4 * * 0     cd $PROJECT_ROOT && log_job "Full Backup" ./backup.sh --type full --rclone

# Daily Health Check (6:00 AM) - Added email alerts
0 6 * * * cd $PROJECT_ROOT && log_job "Health Check" ./health.sh --comprehensive --email --quiet

# Weekly Standard Maintenance (Sunday 5:00 AM)
# Cleans old backups (local & remote), and docker system
0 5 * * 0     cd $PROJECT_ROOT && log_job "Standard Maintenance" sudo ./maintenance.sh --type standard --force

# Weekly System (OS) Package Update (Saturday 3:00 AM)
0 3 * * 6     cd $PROJECT_ROOT && log_job "System Update" sudo ./update.sh --type system --force

# Quarterly Database Maintenance (1st Sunday of Jan, Apr, Jul, Oct at 5:30 AM)
30 5 1-7 * 0   [ \$(date +\%m) -eq 1 -o \$(date +\%m) -eq 4 -o \$(date +\%m) -eq 7 -o \$(date +\%m) -eq 10 ] && cd $PROJECT_ROOT && log_job "DB Maintenance" sudo ./db-maint.sh --force

EOF

    log_success "Cron jobs configuration created in $CRON_FILE"
}

install_cron_jobs() {
    local cron_target_file="/etc/cron.d/vaultwarden-oci-ng"

    if [[ "$DRY_RUN" == "true" ]]; then
        log_info "[DRY RUN] Would install the following system-wide cron jobs to $cron_target_file:"
        cat "$CRON_FILE"
        rm -f "$CRON_FILE"
        return 0
    fi

    log_info "Installing cron jobs to $cron_target_file..."

    if ! mv "$CRON_FILE" "$cron_target_file"; then
        log_error "Failed to move cron file. Check permissions."
        rm -f "$CRON_FILE"
        return 1
    fi

    chmod 644 "$cron_target_file"

    log_success "Cron jobs installed successfully."
    log_info "Cron logs will be written to $PROJECT_ROOT/logs/cron-jobs.log"
    echo ""
    log_info "Complete automation schedule:"
    echo "  • Every 15min: DNS updates (secure, using Docker secrets)"
    echo "  • Weekly Sun 03:00: Cloudflare IP range updates (UFW security sync)"
    echo "  • Daily 02:00: Database backup + rclone sync"
    echo "  • Daily 06:00: Health check + email alerts"
    echo "  • Weekly Sun 04:00: Full backup + rclone sync"
    echo "  • Weekly Sun 05:00: Maintenance cleanup"
    echo "  • Weekly Sat 03:00: System package updates"
    echo "  • Quarterly: Database VACUUM optimization"
}

remove_cron_jobs() {
    local cron_target_file="/etc/cron.d/vaultwarden-oci-ng"

    if [[ "$DRY_RUN" == "true" ]]; then
        log_info "[DRY RUN] Would remove $cron_target_file"
        return 0
    fi

    log_info "Removing VaultWarden-OCI-NG cron jobs..."

    if [[ -f "$cron_target_file" ]]; then
        if ! rm -f "$cron_target_file"; then
            log_error "Failed to remove cron file: $cron_target_file"
            return 1
        fi
        log_success "VaultWarden-OCI-NG cron jobs removed."
    else
        log_info "No cron jobs file found at $cron_target_file. Nothing to remove."
    fi
}

main() {
    log_info "VaultWarden-OCI-NG Cron Setup (Enhanced with Security Automation)"

    if [[ "$DRY_RUN" == "true" ]]; then
        log_warn "DRY RUN MODE - No changes will be made"
    fi

    if [[ "$INSTALL_CRON" == "true" ]]; then
        create_cron_jobs
        install_cron_jobs

    elif [[ "$REMOVE_CRON" == "true" ]]; then
        remove_cron_jobs
    fi
}

main "$@"
