from __future__ import annotations

import os
import tempfile
import unittest
from pathlib import Path
from unittest import mock

from vaultwarden_oci import edge
from vaultwarden_oci.cli import CommandResult


def result(argv, code=0, stdout=""):
    return CommandResult(tuple(argv), "success" if code == 0 else "nonzero", code, stdout, "")


def edge_paths(root: Path) -> edge.EdgePaths:
    return edge.EdgePaths(
        lkg=root / "state/cloudflare.json",
        acquisition=root / "etc/crowdsec/acquis.d/vaultwarden-oci.yaml",
        bouncer_dropin=root / "systemd/bouncer.d/vaultwarden-oci.conf",
        remediation_config=root / "run/bouncer.yaml",
        caddy_log=root / "caddy/access.log",
        remediation_start_token=root / "run/start.token",
        fail_open_confirmation=root / "state/fail-open.json",
    )


def generated_setup_acquisition(source: str) -> str:
    return f'''#
# Configuration generated by "cscli setup".
# Please check your non-generated configuration files to make sure
# the log sources are not acquired twice.
#
# cscli-checksum: a380e4b3fc5e43e510e8287a3fcbe374

filenames:
  - {source}
labels:
  type: syslog
source: file
'''


class CrowdSecScopeTests(unittest.TestCase):
    def test_setup_disables_discovery_keeps_worker_boot_disabled_and_bounds_firewall_to_host(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            paths = edge_paths(root)
            paths.acquisition.parent.mkdir(parents=True, mode=0o755)
            os.chmod(paths.acquisition.parent, 0o755)
            installer = root / "installer.sh"
            installer.write_text("exit 0\n", encoding="utf-8")
            calls: list[tuple[tuple[str, ...], dict[str, str]]] = []

            def runner(argv, *, env=None, cwd=None):
                calls.append((tuple(argv), dict(env or {})))
                return result(argv)

            with mock.patch.object(edge, "_download_installer", return_value=installer):
                edge.setup_crowdsec(paths=paths, runner=runner)

            argv_calls = [call for call, _ in calls]
            install_call = next(call for call in argv_calls if call[:3] == ("apt-get", "install", "-y"))
            install_index = argv_calls.index(install_call)
            self.assertEqual(calls[install_index][1].get("CROWDSEC_SETUP_UNATTENDED_DISABLE"), "1")
            self.assertIn("crowdsec", install_call)
            self.assertIn("crowdsec-cloudflare-worker-bouncer", install_call)
            self.assertIn("crowdsec-firewall-bouncer-nftables", install_call)
            self.assertIn(
                ("systemctl", "disable", "--now", edge.BOUNCER_SERVICE),
                argv_calls,
            )
            self.assertNotIn(
                ("systemctl", "enable", "--now", edge.BOUNCER_SERVICE),
                argv_calls,
            )
            self.assertIn(
                ("systemctl", "enable", "--now", edge.FIREWALL_BOUNCER_SERVICE),
                argv_calls,
            )
            for collection in edge.CROWDSEC_COLLECTIONS:
                self.assertIn(("cscli", "collections", "install", collection), argv_calls)
            self.assertTrue(paths.acquisition.exists())
            firewall_local = paths.acquisition.parent / "crowdsec-firewall-bouncer.yaml.local"
            self.assertTrue(firewall_local.exists())
            policy = firewall_local.read_text(encoding="utf-8")
            self.assertIn("nftables_hooks:\n  - input", policy)
            self.assertNotIn("forward", policy.lower())
            self.assertNotIn("DOCKER-USER", policy)

    def test_setup_removes_cscli_generated_acquisition_residue_before_scope_check(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            paths = edge_paths(root)
            paths.acquisition.parent.mkdir(parents=True)
            generated = (
                paths.acquisition.parent / "setup.linux.yaml",
                paths.acquisition.parent / "setup.sshd.yaml",
            )
            generated[0].write_text(generated_setup_acquisition("/var/log/syslog"), encoding="utf-8")
            generated[1].write_text(generated_setup_acquisition("/var/log/auth.log"), encoding="utf-8")
            installer = root / "installer.sh"
            installer.write_text("exit 0\n", encoding="utf-8")

            def runner(argv, *, env=None, cwd=None):
                return result(argv)

            with mock.patch.object(edge, "_download_installer", return_value=installer):
                edge.setup_crowdsec(paths=paths, runner=runner)

            self.assertTrue(paths.acquisition.exists())
            self.assertFalse(generated[0].exists())
            self.assertFalse(generated[1].exists())

    def test_setup_refuses_unexpected_acquisition_without_deleting_it(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            paths = edge_paths(root)
            paths.acquisition.parent.mkdir(parents=True)
            unexpected = paths.acquisition.parent / "sshd.yaml"
            unexpected.write_text(
                "filenames:\n  - /var/log/auth.log\nlabels:\n  type: syslog\n",
                encoding="utf-8",
            )
            installer = root / "installer.sh"
            installer.write_text("exit 0\n", encoding="utf-8")

            def runner(argv, *, env=None, cwd=None):
                return result(argv)

            with mock.patch.object(edge, "_download_installer", return_value=installer):
                with self.assertRaisesRegex(edge.EdgeError, "unexpected CrowdSec acquisition"):
                    edge.setup_crowdsec(paths=paths, runner=runner)

            self.assertTrue(unexpected.exists())
            self.assertFalse(paths.acquisition.exists())

    def test_setup_filename_alone_cannot_authorize_acquisition_deletion(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            paths = edge_paths(root)
            paths.acquisition.parent.mkdir(parents=True)
            unexpected = paths.acquisition.parent / "setup.operator.yaml"
            unexpected.write_text(
                '# Configuration generated by "cscli setup".\n'
                '# cscli-checksum: not-a-valid-checksum\n'
                'filenames:\n  - /operator/log\nlabels:\n  type: syslog\n',
                encoding="utf-8",
            )
            installer = root / "installer.sh"
            installer.write_text("exit 0\n", encoding="utf-8")

            def runner(argv, *, env=None, cwd=None):
                return result(argv)

            with mock.patch.object(edge, "_download_installer", return_value=installer):
                with self.assertRaisesRegex(edge.EdgeError, "unexpected CrowdSec acquisition"):
                    edge.setup_crowdsec(paths=paths, runner=runner)

            self.assertTrue(unexpected.exists())
            self.assertFalse(paths.acquisition.exists())


if __name__ == "__main__":
    unittest.main()
