from __future__ import annotations

import hashlib
import json
import os
import tempfile
import unittest
from pathlib import Path
from unittest import mock

from vaultwarden_oci import edge
from vaultwarden_oci.cli import CommandResult


def result(argv, code=0, stdout=""):
    return CommandResult(tuple(argv), "success" if code == 0 else "nonzero", code, stdout, "")


def edge_paths(root: Path) -> edge.EdgePaths:
    return edge.EdgePaths(
        lkg=root / "state/cloudflare.json",
        acquisition=root / "etc/crowdsec/acquis.d/vaultwarden-oci.yaml",
        bouncer_dropin=root / "systemd/bouncer.d/vaultwarden-oci.conf",
        remediation_config=root / "run/bouncer.yaml",
        caddy_log=root / "caddy/access.log",
        remediation_start_token=root / "run/start.token",
        fail_open_confirmation=root / "state/fail-open.json",
    )


def generated_setup_acquisition(source: str) -> str:
    content = f'''filenames:
  - {source}
labels:
  type: syslog
source: file
'''
    checksum = hashlib.sha256(content.encode("utf-8")).hexdigest()[:32]
    return f'''#
# Configuration generated by "cscli setup".
# Please check your non-generated configuration files to make sure
# the log sources are not acquired twice. This includes
# the file acquis.yaml created by crowdsec <= 1.7.0.
#
# cscli-checksum: {checksum}

{content}'''


def nft_table(family: str, table: str) -> str:
    chain_base = "crowdsec-chain" if family == "ip" else "crowdsec6-chain"
    return json.dumps(
        {
            "nftables": [
                {
                    "chain": {
                        "family": family,
                        "table": table,
                        "name": f"{chain_base}-input",
                        "type": "filter",
                        "hook": "input",
                        "prio": -10,
                    }
                }
            ]
        }
    )


def successful_setup_runner(calls=None):
    def runner(argv, *, env=None, cwd=None):
        call = tuple(argv)
        if calls is not None:
            calls.append((call, dict(env or {})))
        if call[:4] == ("cscli", "-oraw", "bouncers", "add"):
            return result(argv, stdout="firewall-lapi-key\n")
        if call[:4] == ("cscli", "config", "show", "-oraw"):
            return result(argv, stdout="127.0.0.1:8080\n")
        if call and call[0] == edge.FIREWALL_BOUNCER_BINARY and call[-1:] == ("-T",):
            config = Path(call[call.index("-c") + 1])
            local = Path(str(config) + ".local")
            return result(argv, stdout=local.read_text(encoding="utf-8"))
        if call[:5] == ("nft", "--json", "list", "table", "ip"):
            return result(argv, stdout=nft_table("ip", "crowdsec"))
        if call[:5] == ("nft", "--json", "list", "table", "ip6"):
            return result(argv, stdout=nft_table("ip6", "crowdsec6"))
        return result(argv)

    return runner


class CrowdSecScopeTests(unittest.TestCase):
    def test_setup_disables_discovery_keeps_worker_boot_disabled_and_bounds_firewall_to_host(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            paths = edge_paths(root)
            paths.acquisition.parent.mkdir(parents=True, mode=0o755)
            os.chmod(paths.acquisition.parent, 0o755)
            installer = root / "installer.sh"
            installer.write_text("exit 0\n", encoding="utf-8")
            calls: list[tuple[tuple[str, ...], dict[str, str]]] = []

            with mock.patch.object(edge, "_download_installer", return_value=installer):
                edge.setup_crowdsec(paths=paths, runner=successful_setup_runner(calls))

            argv_calls = [call for call, _ in calls]
            install_call = next(call for call in argv_calls if call[:3] == ("apt-get", "install", "-y"))
            install_index = argv_calls.index(install_call)
            self.assertEqual(calls[install_index][1].get("CROWDSEC_SETUP_UNATTENDED_DISABLE"), "1")
            self.assertIn("crowdsec", install_call)
            self.assertIn("crowdsec-cloudflare-worker-bouncer", install_call)
            self.assertIn("crowdsec-firewall-bouncer-nftables", install_call)
            self.assertIn(
                ("systemctl", "disable", "--now", edge.BOUNCER_SERVICE),
                argv_calls,
            )
            self.assertNotIn(
                ("systemctl", "enable", "--now", edge.BOUNCER_SERVICE),
                argv_calls,
            )
            self.assertIn(
                ("systemctl", "disable", "--now", edge.FIREWALL_BOUNCER_SERVICE),
                argv_calls,
            )
            self.assertIn(
                ("cscli", "-oraw", "bouncers", "add", edge.FIREWALL_BOUNCER_ID),
                argv_calls,
            )
            self.assertIn(
                ("systemctl", "enable", "--now", edge.FIREWALL_BOUNCER_SERVICE),
                argv_calls,
            )
            for collection in edge.CROWDSEC_COLLECTIONS:
                self.assertIn(("cscli", "collections", "install", collection), argv_calls)
            self.assertTrue(paths.acquisition.exists())
            firewall_local = paths.acquisition.parent / "crowdsec-firewall-bouncer.yaml.local"
            self.assertTrue(firewall_local.exists())
            policy = firewall_local.read_text(encoding="utf-8")
            self.assertIn('api_key: "firewall-lapi-key"', policy)
            self.assertIn('api_url: "http://127.0.0.1:8080"', policy)
            self.assertIn("nftables_hooks:\n  - input", policy)
            self.assertNotIn("forward", policy.lower())
            self.assertNotIn("DOCKER-USER", policy)

    def test_setup_removes_cscli_generated_acquisition_residue_before_scope_check(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            paths = edge_paths(root)
            paths.acquisition.parent.mkdir(parents=True)
            generated = (
                paths.acquisition.parent / "setup.linux.yaml",
                paths.acquisition.parent / "setup.sshd.yaml",
            )
            generated[0].write_text(generated_setup_acquisition("/var/log/syslog"), encoding="utf-8")
            generated[1].write_text(generated_setup_acquisition("/var/log/auth.log"), encoding="utf-8")
            installer = root / "installer.sh"
            installer.write_text("exit 0\n", encoding="utf-8")

            with mock.patch.object(edge, "_download_installer", return_value=installer):
                edge.setup_crowdsec(paths=paths, runner=successful_setup_runner())

            self.assertTrue(paths.acquisition.exists())
            self.assertFalse(generated[0].exists())
            self.assertFalse(generated[1].exists())

    def test_setup_refuses_unexpected_acquisition_without_deleting_it(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            paths = edge_paths(root)
            paths.acquisition.parent.mkdir(parents=True)
            unexpected = paths.acquisition.parent / "sshd.yaml"
            unexpected.write_text(
                "filenames:\n  - /var/log/auth.log\nlabels:\n  type: syslog\n",
                encoding="utf-8",
            )
            installer = root / "installer.sh"
            installer.write_text("exit 0\n", encoding="utf-8")

            def runner(argv, *, env=None, cwd=None):
                return result(argv)

            with mock.patch.object(edge, "_download_installer", return_value=installer):
                with self.assertRaisesRegex(edge.EdgeError, "unexpected CrowdSec acquisition"):
                    edge.setup_crowdsec(paths=paths, runner=runner)

            self.assertTrue(unexpected.exists())
            self.assertFalse(paths.acquisition.exists())

    def test_setup_filename_alone_cannot_authorize_acquisition_deletion(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            paths = edge_paths(root)
            paths.acquisition.parent.mkdir(parents=True)
            unexpected = paths.acquisition.parent / "setup.operator.yaml"
            unexpected.write_text(
                '# Configuration generated by "cscli setup".\n'
                '# cscli-checksum: not-a-valid-checksum\n'
                'filenames:\n  - /operator/log\nlabels:\n  type: syslog\n',
                encoding="utf-8",
            )
            installer = root / "installer.sh"
            installer.write_text("exit 0\n", encoding="utf-8")

            def runner(argv, *, env=None, cwd=None):
                return result(argv)

            with mock.patch.object(edge, "_download_installer", return_value=installer):
                with self.assertRaisesRegex(edge.EdgeError, "unexpected CrowdSec acquisition"):
                    edge.setup_crowdsec(paths=paths, runner=runner)

            self.assertTrue(unexpected.exists())
            self.assertFalse(paths.acquisition.exists())

    def test_setup_refuses_modified_cscli_file_with_valid_looking_checksum(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            paths = edge_paths(root)
            paths.acquisition.parent.mkdir(parents=True)
            unexpected = paths.acquisition.parent / "setup.operator.yaml"
            pristine = generated_setup_acquisition("/var/log/auth.log")
            modified = pristine.replace("/var/log/auth.log", "/operator/log")
            unexpected.write_text(modified, encoding="utf-8")
            installer = root / "installer.sh"
            installer.write_text("exit 0\n", encoding="utf-8")

            checksum_line = next(
                line for line in modified.splitlines() if line.startswith(edge.CSCLI_CHECKSUM_PREFIX)
            )
            checksum = checksum_line[len(edge.CSCLI_CHECKSUM_PREFIX):]
            self.assertEqual(len(checksum), 32)
            self.assertTrue(all(char in "0123456789abcdef" for char in checksum))
            self.assertFalse(edge._is_cscli_setup_acquisition(unexpected))

            def runner(argv, *, env=None, cwd=None):
                return result(argv)

            with mock.patch.object(edge, "_download_installer", return_value=installer):
                with self.assertRaisesRegex(edge.EdgeError, "unexpected CrowdSec acquisition"):
                    edge.setup_crowdsec(paths=paths, runner=runner)

            self.assertTrue(unexpected.exists())
            self.assertFalse(paths.acquisition.exists())


if __name__ == "__main__":
    unittest.main()