#!/usr/bin/env bash
# utilities/generate-command-ref.sh — compatibility wrapper for the command
# reference writer used by CI and `make docs`.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
exec bash "${SCRIPT_DIR}/utilities/write-command-reference.sh" "$@"
}

# ── Main ─────────────────────────────────────────────────────────────────────
{
    cat <<'HEADER'
<!-- AUTO-GENERATED by utilities/generate-command-ref.sh — DO NOT EDIT -->
<!-- Regenerate: make docs -->

# Command Reference

This document is auto-generated from the Makefile and script `--help`
output. Do not edit manually; run `make docs` to regenerate.

---

HEADER

    generate_makefile_targets

    echo '---'
    echo ''
    echo '## Entry-Point Scripts'
    echo ''

    # Root-level entry points
    for script in \
        "${SCRIPT_DIR}/setup.sh" \
        "${SCRIPT_DIR}/startup.sh" \
        "${SCRIPT_DIR}/backup.sh" \
        "${SCRIPT_DIR}/restore.sh" \
        "${SCRIPT_DIR}/maintenance.sh" \
        "${SCRIPT_DIR}/edit-secrets.sh" \
        "${SCRIPT_DIR}/dashboard.sh"; do
        [[ -f "$script" ]] && generate_script_help "$script"
    done

    echo '## Utility Scripts'
    echo ''

    # Utility entry points (sorted for deterministic output)
    while IFS= read -r script; do
        [[ -f "$script" ]] && generate_script_help "$script"
    done < <(find "${SCRIPT_DIR}/utilities" -maxdepth 1 -name '*.sh' -type f | sort)

} > "$OUTPUT_FILE"

# Keep the generated Markdown clean for git diff --check.
perl -0pi -e 's/\n+\z/\n/' "$OUTPUT_FILE"

echo "Generated: $OUTPUT_FILE"
