#!/usr/bin/env bash
# utilities/generate-command-ref.sh — Generates docs/COMMAND-REFERENCE.md
# from live Makefile targets and script --help output.
#
# This script is idempotent and safe to run multiple times. Output is
# deterministic for the same input so CI can detect drift.
#
# Usage:
#   bash utilities/generate-command-ref.sh
#   make docs

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_FILE="${SCRIPT_DIR}/docs/COMMAND-REFERENCE.md"

# ── Makefile targets ─────────────────────────────────────────────────────────
generate_makefile_targets() {
    printf '## Makefile Targets\n\n'
    printf '| Target | Description |\n'
    printf '|--------|-------------|\n'
    awk -F ':.*##' '/^[a-zA-Z_-]+:.*##/ { printf "| `make %s` | %s |\n", $1, $2 }' \
        "${SCRIPT_DIR}/Makefile"
    printf '\n'
}

# ── Script help output ──────────────────────────────────────────────────────
generate_script_help() {
    local script="$1"
    local name
    name="$(basename "$script")"

    echo "### ${name}"
    echo ""
    echo '```'
    # Try --help first; if that fails (non-zero exit or empty output) fall back
    # to the 'help' subcommand used by subcommand-driven scripts (e.g. backup-run,
    # restore-run).  Strip log timestamps and ANSI codes so output stays stable
    # across environments and is safe to commit as plain text.
    set +e
    local help_out rc
    help_out="$(timeout 5 bash "$script" --help 2>&1 | head -60 \
        | sed \
            -e 's/\[[0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\}\]/[HH:MM:SS]/g' \
            -e 's/\x1b\[[0-9;]*[mKHF]//g')"
    rc=${PIPESTATUS[0]}
    if [[ $rc -ne 0 || -z "$help_out" ]]; then
        help_out="$(timeout 5 bash "$script" help 2>&1 | head -60 \
            | sed \
                -e 's/\[[0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\}\]/[HH:MM:SS]/g' \
                -e 's/\x1b\[[0-9;]*[mKHF]//g')"
        rc=${PIPESTATUS[0]}
    fi
    set -e
    if [[ -n "$help_out" ]]; then
        echo "$help_out"
    else
        echo '(--help not available or requires root)'
    fi
    echo '```'
    echo ""
}

# ── Main ─────────────────────────────────────────────────────────────────────
{
    cat <<'HEADER'
<!-- AUTO-GENERATED by utilities/generate-command-ref.sh — DO NOT EDIT -->
<!-- Regenerate: make docs -->

# Command Reference

This document is auto-generated from the Makefile and script `--help`
output. Do not edit manually; run `make docs` to regenerate.

---

HEADER

    generate_makefile_targets

    echo '---'
    echo ''
    echo '## Entry-Point Scripts'
    echo ''

    # Root-level entry points
    for script in \
        "${SCRIPT_DIR}/setup.sh" \
        "${SCRIPT_DIR}/startup.sh" \
        "${SCRIPT_DIR}/backup.sh" \
        "${SCRIPT_DIR}/restore.sh" \
        "${SCRIPT_DIR}/maintenance.sh" \
        "${SCRIPT_DIR}/edit-secrets.sh" \
        "${SCRIPT_DIR}/dashboard.sh"; do
        [[ -f "$script" ]] && generate_script_help "$script"
    done

    echo '## Utility Scripts'
    echo ''

    # Utility entry points (sorted for deterministic output)
    while IFS= read -r script; do
        [[ -f "$script" ]] && generate_script_help "$script"
    done < <(find "${SCRIPT_DIR}/utilities" -maxdepth 1 -name '*.sh' -type f | sort)

} > "$OUTPUT_FILE"

echo "Generated: $OUTPUT_FILE"
