#!/usr/bin/env bash
# utilities/write-command-reference.sh — Writes docs/COMMAND-REFERENCE.md
# from live Makefile targets and script help output.
#
# The script writes the generated Markdown through a temporary file and then
# atomically replaces docs/COMMAND-REFERENCE.md. This avoids hand-patching the
# generated file and keeps CI doc-drift checks deterministic.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_FILE="${SCRIPT_DIR}/docs/COMMAND-REFERENCE.md"

show_help() {
    cat <<'HELP'
VaultWarden-OCI Command Reference Writer

USAGE:
    bash utilities/write-command-reference.sh [--help|-h]
    bash utilities/generate-command-ref.sh
    make docs

DESCRIPTION:
    Rebuilds docs/COMMAND-REFERENCE.md from Makefile targets and script help
    output. The file is generated from scratch each time so CI can detect real
    doc drift without carrying over stale or malformed content.

OPTIONS:
    --help, -h      Show this help without rewriting docs
HELP
}

if [[ $# -gt 0 ]]; then
    case "$1" in
        --help|-h|help)
            show_help
            exit 0
            ;;
        *)
            echo "Unknown option: $1" >&2
            show_help >&2
            exit 2
            ;;
    esac
fi

# ── Makefile targets ─────────────────────────────────────────────────────────
generate_makefile_targets() {
    printf '## Makefile Targets\n\n'
    printf '| Target | Description |\n'
    printf '|--------|-------------|\n'
    awk -F ':.*##' '/^[a-zA-Z_-]+:.*##/ { printf "| `make %s` | %s |\n", $1, $2 }' \
        "${SCRIPT_DIR}/Makefile"
    printf '\n'
}

# ── Script help output ──────────────────────────────────────────────────────
sanitize_help_output() {
    # Keep generated docs deterministic: cap help text length, normalize
    # timestamps, strip ANSI escape sequences, and remove NUL bytes using a
    # textual escape pattern so this source file never contains literal NULs.
    head -60 \
        | sed \
            -e 's/\[[0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\}\]/[HH:MM:SS]/g' \
            -e 's/\x1b\[[0-9;]*[mKHF]//g' \
        | perl -pe 's/\x00//g'
}

run_help_command() {
    local script="$1"
    shift

    local raw_out rc
    set +e
    raw_out="$(timeout 5 bash "$script" "$@" 2>&1)"
    rc=$?
    set -e

    HELP_COMMAND_OUTPUT="$(printf '%s\n' "$raw_out" | sanitize_help_output)"
    return "$rc"
}

generate_script_help() {
    local script="$1"
    local name
    name="$(basename "$script")"

    echo "### ${name}"
    echo ""
    echo '```'
    # Try --help first; if that fails (non-zero exit or empty output), fall back
    # to the 'help' subcommand used by subcommand-driven scripts. Capture the
    # command status before truncating output so a successful help page longer
    # than 60 lines is not mistaken for a failure due to SIGPIPE.
    local help_out=""
    if run_help_command "$script" --help && [[ -n "$HELP_COMMAND_OUTPUT" ]]; then
        help_out="$HELP_COMMAND_OUTPUT"
    elif run_help_command "$script" help && [[ -n "$HELP_COMMAND_OUTPUT" ]]; then
        help_out="$HELP_COMMAND_OUTPUT"
    fi

    if [[ -n "$help_out" ]]; then
        printf '%s\n' "$help_out"
    else
        echo '(--help not available or requires root)'
    fi
    echo '```'
    echo ""
}

write_command_reference() {
    cat <<'HEADER'
<!-- AUTO-GENERATED by utilities/write-command-reference.sh — DO NOT EDIT -->
<!-- Regenerate: make docs -->

# Command Reference

This document is auto-generated from the Makefile and script `--help`
output. Do not edit manually; run `make docs` to regenerate.

---

HEADER

    generate_makefile_targets

    echo '---'
    echo ''
    echo '## Entry-Point Scripts'
    echo ''

    # Root-level entry points
    for script in \
        "${SCRIPT_DIR}/setup.sh" \
        "${SCRIPT_DIR}/startup.sh" \
        "${SCRIPT_DIR}/backup.sh" \
        "${SCRIPT_DIR}/restore.sh" \
        "${SCRIPT_DIR}/maintenance.sh" \
        "${SCRIPT_DIR}/edit-secrets.sh" \
        "${SCRIPT_DIR}/dashboard.sh"; do
        [[ -f "$script" ]] && generate_script_help "$script"
    done

    echo '## Utility Scripts'
    echo ''

    # Utility entry points (sorted for deterministic output)
    while IFS= read -r script; do
        [[ -f "$script" ]] && generate_script_help "$script"
    done < <(find "${SCRIPT_DIR}/utilities" -maxdepth 1 -name '*.sh' -type f | sort)
}

tmp_file="$(mktemp "${OUTPUT_FILE}.tmp.XXXXXX")"
trap 'rm -f "$tmp_file"' EXIT

write_command_reference > "$tmp_file"

# Keep the generated Markdown clean for git diff --check.
perl -0pi -e 's/\n+\z/\n/' "$tmp_file"

mv "$tmp_file" "$OUTPUT_FILE"
trap - EXIT

echo "Generated: $OUTPUT_FILE"
