# In fail2ban/action.d/cloudflare.conf
[Definition]
actionstart = 
actionstop = 
actioncheck = 
actionban = curl -s -X POST "https://api.cloudflare.com/client/v4/zones/<cfzone>/firewall/access_rules/rules" \
            -H "Authorization: Bearer $(cat /run/secrets/fail2ban_cloudflare_firewall_token)" \
            -H "Content-Type: application/json" \
            --data '{"mode":"block","configuration":{"target":"ip","value":"<ip>"},"notes":"Blocked by fail2ban"}'

actionunban = # Implementation for unban using the firewall token
