#!/usr/bin/env bash
# lib/migrate.sh — VaultWarden-OCI migration pipeline.
# Sourced by setup-storage.sh; not invoked directly.
[[ -n "${_MV_MIGRATE_LIB_LOADED:-}" ]] && return 0
readonly _MV_MIGRATE_LIB_LOADED=1

# ── Readonly globals ──────────────────────────────────────────────────────────
_MV_TIMESTAMP="$(date +%Y%m%d_%H%M%S)"
readonly _MV_TIMESTAMP
readonly _MV_LOCK_FILE="/run/lock/vaultwarden-migrate.lock"
readonly _MV_LOG_MAX_BYTES=$(( 10 * 1024 * 1024 ))   # 10 MiB — rotate beyond this
readonly _MV_VERIFY_TOLERANCE_PCT=1                    # informational byte-delta threshold

# Keep the state file in PROJECT_ROOT because PROJECT_STATE_DIR may change during migration.
readonly _MV_STATE_FILE="${PROJECT_ROOT}/.migrate-volume.state"

# Exclude paths that must not be copied to the target.
readonly -a _MV_RSYNC_EXCLUDES=(
    "lost+found/"       # ext4 fsck directory — permission errors on some kernels
    "*.sock"            # dead runtime sockets confuse service startup diagnostics
    "*.pid"             # PID files are always stale after stack stop
    "*.sqlite3-wal"     # SQLite WAL — a non-empty WAL after stack stop indicates a hot DB
    "*.sqlite3-shm"     # SQLite shared-memory file — always accompanies the WAL
)

# Protect the target-owned volume marker from both transfer and deletion. The
# rule excludes a source marker and prevents --delete-excluded from removing the
# protected marker that setup_data_volume() creates on the target.
readonly -a _MV_RSYNC_PROTECTS=(
    ".vw-data-volume"
)

# Systemd ReadWritePaths drop-ins are regenerated by utilities/setup-systemd.sh
# after migration env sync, so migration does not maintain a duplicate unit list.

# ── Mutable globals ───────────────────────────────────────────────────────────
_MV_SUBCOMMAND="run"
_MV_SOURCE=""
_MV_TARGET=""
_MV_DEVICE=""
_MV_DIRECTION="boot-to-block"   # migration direction; override with --direction
_MV_CURRENT_STEP=""             # tracks active pipeline step for error messages
_MV_SKIP_STACK_STOP=false
_MV_DELETE_SOURCE=false
_MV_FORCE=false
_MV_FORCE_FORMAT=false
_MV_YES=false
_MV_LOG_FILE=""
_MV_BACKUP_DIR_CUSTOM_WARNING=""
_MV_START_POLICY=""
# Mutable copy of the original run timestamp; updated from state on resume.
_MV_RUN_TIMESTAMP="${_MV_TIMESTAMP}"

_MV_START_TIME="${SECONDS}"   # bash built-in — seconds since shell started

_MV_LOCK_FD=""

# ── Utility helpers ───────────────────────────────────────────────────────────
_mv_elapsed() {
    local elapsed=$(( SECONDS - _MV_START_TIME ))
    printf '%dm%02ds' $(( elapsed / 60 )) $(( elapsed % 60 ))
}

# Human-readable byte formatter (replaces numfmt — works on GNU/BusyBox)
_mv_fmt_bytes() {
    # Usage: _mv_fmt_bytes <bytes>
    # Prints a human-readable IEC byte count (e.g. "1.5 GiB").
    # Pure awk — no numfmt dependency; portable to GNU coreutils and BusyBox.
    awk -v n="$1" 'BEGIN {
        split("B KiB MiB GiB TiB", u, " ")
        v = n; i = 1
        while (v >= 1024 && i < 5) { v /= 1024; i++ }
        printf "%.1f %s", v, u[i]
    }'
}

_mv_du_bytes() {
    local path="$1" bytes

    bytes="$(du -sb "$path" 2>/dev/null | awk 'NR == 1 {print $1}')" || bytes=""
    if [[ "$bytes" =~ ^[0-9]+$ ]]; then
        printf '%s\n' "$bytes"
        return 0
    fi

    find "$path" -type f -exec sh -c '
        for file do
            stat -c %s "$file" 2>/dev/null \
                || stat -f %z "$file" 2>/dev/null \
                || printf "0\n"
        done
    ' sh {} + | awk '{sum += $1} END {printf "%.0f\n", sum}'
}

_mv_realpath() {
    local path="$1" part
    local -a parts=() stack=()

    if command realpath -m "$path" >/dev/null 2>&1; then
        command realpath -m "$path"
        return 0
    fi

    [[ "$path" == /* ]] || path="$PWD/$path"
    IFS='/' read -r -a parts <<< "$path"
    for part in "${parts[@]}"; do
        case "$part" in
            ""|.) ;;
            ..)
                if (( ${#stack[@]} > 0 )); then
                    unset 'stack[${#stack[@]}-1]'
                fi
                ;;
            *) stack+=("$part") ;;
        esac
    done

    if (( ${#stack[@]} == 0 )); then
        printf '/\n'
    else
        local IFS=/
        printf '/%s\n' "${stack[*]}"
    fi
}

_mv_acquire_lock() {
    local lock_fd
    mkdir -p "$(dirname "${_MV_LOCK_FILE}")"
    : >> "${_MV_LOCK_FILE}"
    chmod 0600 "${_MV_LOCK_FILE}"
    exec {lock_fd}>"${_MV_LOCK_FILE}"
    flock -n "${lock_fd}" || {
        log_error "Another migration is already running (lock held: ${_MV_LOCK_FILE})."
        log_error "Run: sudo utilities/setup-storage.sh migrate status"
        log_error "Check active operations with: sudo make operations"
        exit 1
    }
    _MV_LOCK_FD="${lock_fd}"
}

_mv_release_lock() {
    [[ -n "${_MV_LOCK_FD:-}" ]] && {
        flock -u "${_MV_LOCK_FD}"
        eval "exec ${_MV_LOCK_FD}>&-"
        _MV_LOCK_FD=""
    }
}

_mv_cleanup() {
    _mv_release_lock
    _mv_log info "Elapsed: $(_mv_elapsed)"
}

_mv_require_root() {
    [[ "${EUID}" -eq 0 ]] || {
        log_error "This script must be run as root: sudo utilities/setup-storage.sh migrate $*"
        exit 1
    }
}

_mv_log() {
    # Passthrough to lib/common.sh log functions AND write to log file.
    # Usage: _mv_log <level> <message>
    # level: info | warn | error | success
    local level="$1"; shift
    local msg="$*"
    "log_${level}" "${msg}"
    printf '[%s] [%s] %s\n' \
        "$(date '+%Y-%m-%d %H:%M:%S')" \
        "${level^^}" \
        "${msg}" >> "${_MV_LOG_FILE:-${PROJECT_ROOT}/logs/migrate-volume.log}"
}

_mv_on_err() {
    local rc="$1" lineno="$2"
    local _step_ctx=""
    [[ -n "${_MV_CURRENT_STEP:-}" ]] && _step_ctx=" during [${_MV_CURRENT_STEP}] step"
    _mv_log error "Unexpected error${_step_ctx} at line ${lineno} (exit ${rc}). Migration halted."
    _mv_log error "Resume with: sudo utilities/setup-storage.sh migrate resume"
    _mv_log error "Abort with:  sudo utilities/setup-storage.sh migrate abort"
    # Do NOT call _mv_cleanup here — EXIT trap fires after ERR trap.
}

_mv_open_log() {
    # Determine log file path (--log-file overrides default).
    # Keep logs under PROJECT_ROOT/logs, never PROJECT_STATE_DIR/logs.
    # PROJECT_STATE_DIR is the migration source and may be renamed or deleted mid-run
    # (step 6 rename_source / step 6a delete_source). Using PROJECT_ROOT keeps the log
    # file alive for the full duration of the migration, including --delete-source runs.
    if [[ -z "${_MV_LOG_FILE:-}" ]]; then
        local log_dir="${PROJECT_ROOT}/logs"
        mkdir -p "${log_dir}" 2>/dev/null || log_dir="${PROJECT_ROOT}"
        _MV_LOG_FILE="${log_dir}/migrate-volume-${_MV_TIMESTAMP}.log"
    fi

    # Log rotation: if any existing migrate-volume log exceeds _MV_LOG_MAX_BYTES,
    # rotate it before this run creates a fresh file.
    local existing_log
    for existing_log in "$(dirname "${_MV_LOG_FILE}")"/migrate-volume-*.log; do
        [[ -f "${existing_log}" ]] || continue
        local size
        size="$(stat -c '%s' "${existing_log}" 2>/dev/null || echo 0)"
        if (( size > _MV_LOG_MAX_BYTES )); then
            mv "${existing_log}" "${existing_log}.${_MV_TIMESTAMP}"
            log_info "Rotated log: ${existing_log} → ${existing_log}.${_MV_TIMESTAMP}"
        fi
    done

    [[ "${DRY_RUN}" == "true" ]] || touch "${_MV_LOG_FILE}"

    _mv_log info "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    _mv_log info "  migrate mode — $(date '+%Y-%m-%d %H:%M:%S %Z')"
    _mv_log info "  Log file: ${_MV_LOG_FILE}"
    _mv_log info "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
}

_mv_state_write() {
    # Usage: _mv_state_write KEY [VALUE]
    local key="$1" value="${2:-true}"
    local tmp
    tmp="$(mktemp "${_MV_STATE_FILE}.XXXXXX")"
    if [[ -f "${_MV_STATE_FILE}" ]]; then
        grep -v "^${key}=" "${_MV_STATE_FILE}" > "${tmp}" 2>/dev/null || true
    fi
    printf '%s=%s\n' "${key}" "${value}" >> "${tmp}"
    chmod 0600 "${tmp}"
    mv -f "${tmp}" "${_MV_STATE_FILE}"
}

_mv_state_read() {
    # Usage: _mv_state_read KEY
    [[ -f "${_MV_STATE_FILE}" ]] || return 0
    grep "^${1}=" "${_MV_STATE_FILE}" 2>/dev/null | cut -d= -f2- | tail -1
}

_mv_state_has() {
    # Usage: _mv_state_has KEY — returns 0 if key is present and non-empty
    local val
    val="$(_mv_state_read "$1")"
    [[ -n "${val}" ]]
}

_mv_state_clear() {
    rm -f "${_MV_STATE_FILE}"
}

_mv_confirm() {
    # Usage: _mv_confirm "Prompt text"
    # Returns 0 if confirmed, exits 1 if declined.
    # Skipped when --yes is set.
    [[ "${_MV_YES:-false}" == "true" ]] && return 0
    local reply
    if ! read -r -t 300 -p "${1} [yes/no] (default: no): " reply; then
        printf '\n' >&2
        log_error "No confirmation received within 5 minutes. Aborted."
        exit 1
    fi
    [[ "${reply,,}" =~ ^y(es)?$ ]] || { log_error "Aborted by operator."; exit 1; }
}

_mv_confirm_by_typing() {
    # Usage: _mv_confirm_by_typing "Prompt" "expected string"
    # Always interactive — --yes does NOT bypass this.
    local prompt="$1" expected="$2" reply
    if ! read -r -t 300 -p "${prompt} Type exactly '${expected}' to confirm: " reply; then
        printf '\n' >&2
        log_error "No confirmation received within 5 minutes. Aborted."
        exit 1
    fi
    [[ "${reply}" == "${expected}" ]] || {
        log_error "Confirmation did not match. Aborted."
        exit 1
    }
}

_mv_warn_fstab_entries() {
    # Scans /etc/fstab for entries that reference _MV_SOURCE (the old data
    # path). These could auto-mount the old location at boot and shadow the
    # new mount point. Entries for _MV_TARGET are intentionally excluded: the
    # target's fstab entry is the correct, required entry after a block-device
    # migration and must NOT be removed.
    [[ -f /etc/fstab ]] || return 0
    [[ -n "${_MV_SOURCE:-}" ]] || return 0

    local line found=false
    while IFS= read -r line; do
        [[ "${line}" =~ ^[[:space:]]*# ]] && continue
        [[ -z "${line//[[:space:]]/}" ]]  && continue
        if [[ "${line}" == *"${_MV_SOURCE}"* ]]; then
            if [[ "${found}" == "false" ]]; then
                _mv_log warn "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
                _mv_log warn "  ⚠  FSTAB WARNING: /etc/fstab still references the old source path"
                found=true
            fi
            _mv_log warn "    ${line}"
        fi
    done < /etc/fstab

    if [[ "${found}" == "true" ]]; then
        _mv_log warn "  These entries may auto-mount the old source location at boot."
        _mv_log warn "  Review them and remove any that are no longer needed. Example:"
        local _esc_src="${_MV_SOURCE//\\/\\\\}"
        _esc_src="${_esc_src//./\\.}"
        _esc_src="${_esc_src//|/\\|}"
        _mv_log warn "    sed -i '\\|${_esc_src}|d' /etc/fstab"
        _mv_log warn "  (Verify the resulting fstab is correct before rebooting.)"
        _mv_log warn "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    fi
}

# ── Interactive block device selector ────────────────────────────────────────
_mv_select_device() {
    # Presents a numbered list of block devices and partitions using lsblk.
    # For boot-to-block: marks boot devices [boot] and warns against selecting them.
    # For block-to-boot: shows only mounted volumes whose filesystem identity
    #   validates against that exact device; auto-populates _MV_SOURCE after selection.
    # Skips if --device was already provided, or subcommand is not 'run'.
    [[ -n "${_MV_DEVICE:-}" ]] && return 0
    [[ "${_MV_SUBCOMMAND}" == "run" ]] || return 0
    [[ -n "${_MV_TARGET:-}" && "${_MV_DIRECTION}" == "boot-to-block" ]] && return 0

    log_info "Detecting block devices using lsblk..."
    printf '\n'

    local -a dev_names dev_sizes dev_mounts dev_types
    local name size mount type

    while IFS=' ' read -r name size mount type; do
        [[ -z "${name}" ]] && continue
        dev_names+=( "/dev/${name}" )
        dev_sizes+=( "${size}" )
        dev_mounts+=( "${mount}" )
        dev_types+=( "${type}" )
    done < <(lsblk -o NAME,SIZE,MOUNTPOINT,TYPE -rn 2>/dev/null)

    if (( ${#dev_names[@]} == 0 )); then
        log_error "No block devices found via lsblk. Ensure the target disk is attached."
        return 1
    fi

    local root_source root_dev
    root_source="$(findmnt -n -o SOURCE / 2>/dev/null || true)"
    root_dev="$(lsblk -no PKNAME "${root_source}" 2>/dev/null \
        || lsblk -no NAME "${root_source}" 2>/dev/null \
        || true)"
    [[ -n "${root_dev}" ]] && root_dev="/dev/${root_dev}"

    # Build the filtered display list.
    # block-to-boot: only mounted volumes with a valid filesystem identity.
    # boot-to-block: all devices (existing behaviour).
    local -a display_indices=()
    local _di
    for (( _di=0; _di<${#dev_names[@]}; _di++ )); do
        if [[ "${_MV_DIRECTION}" == "block-to-boot" ]]; then
            local _mnt="${dev_mounts[$_di]:-}"
            [[ -n "${_mnt}" && "${_mnt}" != "-" ]] || continue
            storage_validate_volume_identity "${_mnt}" "${dev_names[$_di]}" >/dev/null 2>&1 \
                && display_indices+=( "$_di" )
        else
            display_indices+=( "$_di" )
        fi
    done

    if (( ${#display_indices[@]} == 0 )); then
        if [[ "${_MV_DIRECTION}" == "block-to-boot" ]]; then
            log_error "No mounted VaultWarden data volume with a valid filesystem identity was found."
            log_error "Verify the configured source volume and repair identity only after proving the disk."
            log_error "You may also specify the expected source device explicitly with --device."
        else
            log_error "No block devices found via lsblk. Ensure the target disk is attached."
        fi
        return 1
    fi

    local _idx tags mount_display identity_tag
    local _dn=0
    local -a display_map=()
    for _idx in "${display_indices[@]}"; do
        tags=""
        identity_tag=""
        if [[ "${dev_mounts[$_idx]}" == "/" ]] \
                || { [[ -n "${root_dev}" ]] \
                     && [[ "${#dev_names[$_idx]}" -ge "${#root_dev}" ]] \
                     && [[ "${dev_names[$_idx]:0:${#root_dev}}" == "${root_dev}" ]]; } \
                || [[ -n "${root_source}" && "${root_source}" == "${dev_names[$_idx]}" ]]; then
            tags="${tags} [boot]"
        fi
        if [[ "${dev_types[$_idx]}" == "part" ]]; then
            tags="${tags} [part]"
        fi
        local _mnt_check="${dev_mounts[$_idx]:-}"
        if [[ -n "${_mnt_check}" && "${_mnt_check}" != "-" ]] \
                && storage_validate_volume_identity "${_mnt_check}" "${dev_names[$_idx]}" >/dev/null 2>&1; then
            identity_tag=" [vaultwarden-data]"
        fi

        mount_display="${dev_mounts[$_idx]:-  -}"
        printf '  %d) %-14s  size: %-8s  mount: %-20s%s%s\n' \
            $(( _dn + 1 )) \
            "${dev_names[$_idx]}" \
            "${dev_sizes[$_idx]}" \
            "${mount_display}" \
            "${tags}" \
            "${identity_tag}"
        display_map+=( "$_idx" )
        (( _dn++ )) || true
    done

    printf '\n'
    if [[ "${_MV_DIRECTION}" == "block-to-boot" ]]; then
        printf '  Note: Only mounted volumes with a valid VaultWarden filesystem identity are shown above.\n'
        printf '  Select the volume containing the data you want to move back to the boot disk.\n'
        printf '\n'
        log_warn "Select SOURCE block device to migrate FROM (the data volume to vacate):"
    else
        printf '  Note: Cloud providers often attach volumes as a partition (e.g. /dev/sdb1)\n'
        printf '  rather than the whole disk (/dev/sdb). Both are listed above — select\n'
        printf '  whichever device path your cloud provider assigned to the new volume.\n'
        printf '\n'
        log_warn "Select TARGET block device for migration (DO NOT choose [boot]):"
    fi

    local choice
    while true; do
        read -r -p "  Device number [1-${#display_map[@]}]: " choice
        if [[ "${choice}" =~ ^[0-9]+$ ]] \
                && (( choice >= 1 && choice <= ${#display_map[@]} )); then
            local _real_idx="${display_map[$(( choice - 1 ))]}"
            _MV_DEVICE="${dev_names[${_real_idx}]}"
            if [[ "${_MV_DIRECTION}" != "block-to-boot" ]]; then
                if [[ "${dev_mounts[${_real_idx}]}" == "/" ]] \
                        || { [[ -n "${root_dev}" ]] \
                             && [[ "${#_MV_DEVICE}" -ge "${#root_dev}" ]] \
                             && [[ "${_MV_DEVICE:0:${#root_dev}}" == "${root_dev}" ]]; } \
                        || [[ -n "${root_source}" && "${root_source}" == "${_MV_DEVICE}" ]]; then
                    log_error "You selected the boot device. Aborting to prevent data loss."
                    exit 1
                fi
            fi
            if [[ "${_MV_DIRECTION}" == "block-to-boot" && -z "${_MV_SOURCE:-}" ]]; then
                _MV_SOURCE="${dev_mounts[${_real_idx}]}"
                log_info "Source (block volume mount): ${_MV_SOURCE}"
            fi
            break
        fi
        log_warn "Invalid selection. Enter a number between 1 and ${#display_map[@]}."
    done

    printf '\n'
    if [[ "${_MV_DIRECTION}" == "block-to-boot" ]]; then
        log_info "Selected source device: ${_MV_DEVICE} (mounted at ${_MV_SOURCE:-unknown})"
    else
        log_info "Selected target device: ${_MV_DEVICE}"
    fi
}

_mv_prompt_target() {
    [[ -n "${_MV_TARGET:-}" ]] && return 0
    [[ "${_MV_SUBCOMMAND}" == "run" ]] || return 0

    local default_mount reply
    if [[ "${_MV_DIRECTION}" == "block-to-boot" ]]; then
        default_mount="${PROJECT_STATE_DIR:-${_VW_DEFAULT_STATE_DIR}}"
    else
        default_mount="${DATA_VOLUME_MOUNT:-${_VW_DEFAULT_DATA_MOUNT}}"
    fi

    printf '\n'
    read -r -p "  Enter target path [${default_mount}]: " reply
    _MV_TARGET="${reply:-${default_mount}}"
    _MV_TARGET="$(_mv_realpath "${_MV_TARGET}")"
    log_info "Using target path: ${_MV_TARGET}"
    printf '\n'
}

_mv_print_preflight_summary() {
    local mode
    if [[ -n "${_MV_DEVICE}" ]]; then
        mode="block-device (format + rsync)"
    else
        mode="directory-to-directory (rsync only, no format)"
    fi

    printf '\n'
    printf '╔═══════════════════════════════════════════════════════════════╗\n'
    printf '║  Migration Pre-flight Summary                                 ║\n'
    printf '╠═══════════════════════════════════════════════════════════════╣\n'
    printf '  %-20s %s\n'  "Mode:"          "${mode}"
    printf '  %-20s %s\n'  "Source:"        "${_MV_SOURCE}"
    printf '  %-20s %s\n'  "Target:"        "${_MV_TARGET}"
    printf '  %-20s %s\n'  "Device:"        "${_MV_DEVICE:-(none — dir-to-dir)}"
    printf '  %-20s %s\n'  "Stack stop:"    "$( [[ "${_MV_SKIP_STACK_STOP}" == 'true' ]] && echo 'SKIPPED (--skip-stack-stop)' || echo 'yes' )"
    printf '  %-20s %s\n'  "Delete source:" "$( [[ "${_MV_DELETE_SOURCE}" == 'true' ]] && echo 'yes (will prompt)' || echo 'no' )"
    printf '  %-20s %s\n'  "Format blank device:" "$( [[ "${_MV_FORCE_FORMAT}" == 'true' ]] && echo 'yes' || echo 'no' )"
    printf '  %-20s %s\n'  "Dry run:"       "${DRY_RUN}"
    printf '  %-20s %s\n'  "Log file:"      "${_MV_LOG_FILE}"
    printf '╚═══════════════════════════════════════════════════════════════╝\n'
    printf '\n'

    if [[ -z "${_MV_DEVICE}" && -d "${_MV_TARGET}" ]]; then
        local _target_item_count
        _target_item_count="$(find "${_MV_TARGET}" -maxdepth 1 -mindepth 1 2>/dev/null | wc -l | tr -d ' ')"
        if (( _target_item_count > 0 )); then
            printf '  ⚠  WARNING: Target directory is non-empty (%s item(s)).\n' "${_target_item_count}"
            printf '     rsync --delete will REMOVE files in target that do not exist in source.\n'
            printf '     Run with --dry-run first to inspect changes before proceeding.\n'
            printf '\n'
        fi
    fi

    if [[ "${_MV_YES:-false}" == "true" ]]; then
        _mv_log info "Non-interactive mode (--yes): proceeding without confirmation."
        return 0
    fi

    _mv_confirm "Confirm the above and start migration."
}


_mv_running_container_count() {
    docker compose ps --status running --quiet 2>/dev/null \
        | awk 'NF { count++ } END { print count + 0 }'
}

_mv_ensure_stack_stopped_for_rsync() {
    # Resume safety guard: never trust STEP_STOP_DONE alone. A maintenance command
    # or operator action may have restarted containers after the stop checkpoint.
    [[ "${_MV_SKIP_STACK_STOP}" == "true" ]] && return 0
    [[ "${DRY_RUN}" == "true" ]] && {
        _mv_log info "[DRY RUN] would: re-check Docker stack is stopped immediately before rsync"
        return 0
    }

    local running_before running_after
    running_before="$(_mv_running_container_count)"
    if (( running_before == 0 )); then
        _mv_log info "Pre-rsync stack safety check passed: no running containers."
        return 0
    fi

    _mv_log warn "Pre-rsync stack safety check found ${running_before} running container(s)."
    _mv_log warn "The stack may have been restarted after the saved stop checkpoint; stopping it again before rsync."
    stop_services || {
        _mv_log error "Failed to stop Docker stack immediately before rsync."
        _mv_log error "Refusing to rsync while containers may be running. Stop the stack and resume."
        return 1
    }

    running_after="$(_mv_running_container_count)"
    if (( running_after > 0 )); then
        _mv_log error "Docker stack still has ${running_after} running container(s) after stop attempt."
        _mv_log error "Refusing to rsync live data. Stop containers manually, then resume."
        return 1
    fi

    _mv_log success "Pre-rsync stack safety check passed after re-stopping the stack."
}

_mv_add_rsync_filters() {
    local -n _flags_ref=$1
    local excl protect
    for protect in "${_MV_RSYNC_PROTECTS[@]}"; do
        _flags_ref+=("--filter=protect ${protect}")
        _flags_ref+=("--exclude=${protect}")
    done
    for excl in "${_MV_RSYNC_EXCLUDES[@]}"; do
        _flags_ref+=("--filter=protect ${excl}")
        _flags_ref+=("--exclude=${excl}")
    done
}

_mv_check_disk_space() {
    local source="$1" target="$2"
    local src_bytes avail_bytes required_bytes

    src_bytes="$(_mv_du_bytes "${source}/")"
    avail_bytes="$(df -Pk "${target}" | awk 'NR==2 {print $4 * 1024}')"
    required_bytes=$(( src_bytes + src_bytes / 10 ))

    _mv_log info "Disk space check:"
    _mv_log info "  Source size  : $(_mv_fmt_bytes "${src_bytes}")"
    _mv_log info "  Required     : $(_mv_fmt_bytes "${required_bytes}") (source + 10%)"
    _mv_log info "  Target avail : $(_mv_fmt_bytes "${avail_bytes}")"

    if (( avail_bytes < required_bytes )); then
        _mv_log error "Insufficient space on target."
        _mv_log error "  Need : $(_mv_fmt_bytes "${required_bytes}")"
        _mv_log error "  Have : $(_mv_fmt_bytes "${avail_bytes}")"
        return 1
    fi

    _mv_log success "Disk space OK."
}

_mv_check_stale_backup() {
    local backup_base_dir newest newest_ts now_ts age_hours

    backup_base_dir="${BACKUP_DIR:-${PROJECT_STATE_DIR:-${_VW_DEFAULT_STATE_DIR}}/backups}"

    newest="$(find "${backup_base_dir}" -name "*.age" -type f -print0 2>/dev/null \
        | xargs -r -0 stat -c '%Y %n' 2>/dev/null \
        | sort -rn \
        | head -1 \
        | awk '{print $2}')" || newest=""

    if [[ -z "${newest}" ]]; then
        _mv_log warn "No backups found. Strongly consider running: sudo ./backup.sh full"
        return 0
    fi

    newest_ts="$(stat -c '%Y' "${newest}" 2>/dev/null || echo 0)"
    now_ts="$(date +%s)"
    age_hours=$(( (now_ts - newest_ts) / 3600 ))

    if (( age_hours > 24 )); then
        _mv_log warn "Newest backup is ${age_hours}h old: ${newest}"
        _mv_log warn "Consider running: sudo ./backup.sh full"
    else
        _mv_log info "Backup age OK: ${age_hours}h old — ${newest}"
    fi
}

_mv_set_env_var() {
    local key="$1" value="$2"
    local env_file="${PROJECT_ROOT}/.env"

    if [[ "${DRY_RUN}" == "true" ]]; then
        _mv_log info "[DRY RUN] would: set: ${key}=${value}"
        return 0
    fi

    _set_env_var "$key" "$value" "$env_file" || return $?
    _mv_log info ".env updated: ${key}=${value}"
}

_mv_require_value() {
    local opt="$1" value="${2-}"
    if [[ -z "$value" || "$value" == --* ]]; then
        log_error "$opt requires a value."
        _mv_usage
        exit 2
    fi
}

_mv_usage() {
cat << 'EOF' | sed "s|@DEFAULT_DATA_MOUNT@|${_VW_DEFAULT_DATA_MOUNT}|g"
VaultWarden-OCI Volume Migration (via setup-storage.sh migrate)

USAGE:
  sudo utilities/setup-storage.sh migrate <subcommand> [OPTIONS]

SUBCOMMANDS:
  run      Execute the full migration pipeline (default)
  resume   Resume a previously interrupted migration
  status   Show current migration state
  abort    Roll back an in-progress migration
  verify   Re-run byte-count verification only (non-destructive)

OPTIONS (run):
  --source  <path>   Source directory  (default: current PROJECT_STATE_DIR from .env)
  --target  <path>   Destination path  (prompted interactively if omitted)
  --device  <dev>    Block device (e.g. /dev/sdb)
                     Prompted interactively via lsblk if omitted.
                     Omit entirely for directory-to-directory migration.
  --direction <dir>  Migration direction (default: boot-to-block):
                     boot-to-block  — move data from boot volume to a dedicated
                                      block device (forward migration).
                     block-to-boot  — reverse: move data from block device back
                                      to the boot volume (e.g. before detaching
                                      the disk for maintenance or replacement).
  --skip-stack-stop  Do not stop the Docker stack before migrating.
                     Requires explicit runtime confirmation. Use with caution.
                     Cannot be combined with --yes (non-interactive mode).
  --delete-source    Delete renamed source after successful verification.
                     Always requires typing the path to confirm.
  --dry-run          Print all actions without executing them.
  --force            Skip the pre-migration backup confirmation prompt.
  --force-format     Authorize formatting a blank/signature-free target block
                     device during migrate mode. Does not skip backup prompts.
  --yes              Answer yes to all confirmations (except --delete-source).
                     Requires --target when used (non-interactive mode).
                     Cannot be combined with --skip-stack-stop.
  --start-policy <mode>
                     Service start policy after migration: auto | ask | manual.
  --start            Alias for --start-policy auto.
  --no-start         Alias for --start-policy manual.
  --log-file <path>  Override default log file path.
  --help             Show this help and exit.

OPTIONS (resume):
  --dry-run          Print resume actions without executing them.
  --force            Skip the backup confirmation if that step has not completed.
  --force-format     Preserve or upgrade authorization for formatting a blank target.
  --yes              Answer yes to confirmations that are safe to automate.
  --start-policy <mode>
                     Service start policy if resume reaches the start step.
  --start            Alias for --start-policy auto.
  --no-start         Alias for --start-policy manual.

NOTE:
  status, abort, and verify read the recorded migration state and do not accept
  behavior options.

EXAMPLES:
  # Interactive (prompts for device and mount point)
  sudo utilities/setup-storage.sh migrate run

  # Non-interactive: boot volume → dedicated data volume
  sudo utilities/setup-storage.sh migrate run \
    --source /var/lib/vaultwarden \
    --target @DEFAULT_DATA_MOUNT@ \
    --device /dev/sdb \
    --force-format \
    --yes

  # Reverse migration: move data from block volume back to boot volume
  sudo utilities/setup-storage.sh migrate run \
    --direction block-to-boot \
    --target /var/lib/vaultwarden \
    --device /dev/sdb

  # Directory-to-directory (no device, no format step)
  sudo utilities/setup-storage.sh migrate run \
    --source /var/lib/vaultwarden \
    --target /mnt/vw-data2

  # Dry run first
  sudo utilities/setup-storage.sh migrate run \
    --source /var/lib/vaultwarden \
    --target @DEFAULT_DATA_MOUNT@ \
    --device /dev/sdb \
    --dry-run

  # Resume after interruption
  sudo utilities/setup-storage.sh migrate resume

  # Check status
  sudo utilities/setup-storage.sh migrate status

  # Abort and roll back
  sudo utilities/setup-storage.sh migrate abort
EOF
}

_mv_parse_args() {
    _MV_SUBCOMMAND="run"
    _MV_SOURCE=""
    _MV_TARGET=""
    _MV_DEVICE=""
    _MV_DIRECTION="boot-to-block"
    _MV_SKIP_STACK_STOP=false
    _MV_DELETE_SOURCE=false
    _MV_FORCE=false
    _MV_FORCE_FORMAT=false
    _MV_YES=false
    _MV_LOG_FILE=""
    _MV_START_POLICY=""
    local -a _mv_seen_options=()

    if [[ $# -gt 0 && "${1}" != --* ]]; then
        _MV_SUBCOMMAND="$1"
        shift
    fi

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --source)
                _mv_seen_options+=("$1")
                _mv_require_value "$1" "${2-}"
                _MV_SOURCE="$2"
                shift 2
                ;;
            --target)
                _mv_seen_options+=("$1")
                _mv_require_value "$1" "${2-}"
                _MV_TARGET="$2"
                shift 2
                ;;
            --device)
                _mv_seen_options+=("$1")
                _mv_require_value "$1" "${2-}"
                _MV_DEVICE="$2"
                shift 2
                ;;
            --log-file)
                _mv_seen_options+=("$1")
                _mv_require_value "$1" "${2-}"
                _MV_LOG_FILE="$2"
                shift 2
                ;;
            --skip-stack-stop)
                _mv_seen_options+=("$1")
                _MV_SKIP_STACK_STOP=true
                shift
                ;;
            --delete-source)
                _mv_seen_options+=("$1")
                _MV_DELETE_SOURCE=true
                shift
                ;;
            --dry-run)
                _mv_seen_options+=("$1")
                DRY_RUN=true
                shift
                ;;
            --force)
                _mv_seen_options+=("$1")
                _MV_FORCE=true
                shift
                ;;
            --force-format)
                _mv_seen_options+=("$1")
                _MV_FORCE_FORMAT=true
                shift
                ;;
            --yes)
                _mv_seen_options+=("$1")
                _MV_YES=true
                shift
                ;;
            --start-policy)
                _mv_seen_options+=("$1")
                if [[ $# -lt 2 || "${2:-}" == --* ]]; then
                    log_error "--start-policy requires a value: auto | ask | manual"
                    _mv_usage
                    exit 2
                fi
                _MV_START_POLICY="$2"
                shift 2
                ;;
            --start)
                _mv_seen_options+=("$1")
                _MV_START_POLICY="auto"
                shift
                ;;
            --no-start)
                _mv_seen_options+=("$1")
                _MV_START_POLICY="manual"
                shift
                ;;
            --direction)
                _mv_seen_options+=("$1")
                _mv_require_value "$1" "${2-}"
                case "$2" in
                    boot-to-block|block-to-boot)
                        _MV_DIRECTION="$2"
                        ;;
                    *)
                        log_error "Unknown --direction value: '$2'"
                        log_error "Valid values: boot-to-block (default) | block-to-boot"
                        exit 1
                        ;;
                esac
                shift 2
                ;;
            --help|-h)
                _mv_usage
                exit 0
                ;;
            *)
                log_error "Unknown option: $1"
                _mv_usage
                exit 1
                ;;
        esac
    done

    case "${_MV_SUBCOMMAND}" in
        run)
            if [[ "${_MV_YES:-false}" == "true" && -z "${_MV_TARGET}" ]]; then
                log_error "--target is required when using --yes (non-interactive mode)."
                exit 1
            fi
            if [[ "${_MV_YES:-false}" == "true" && "${_MV_SKIP_STACK_STOP}" == "true" ]]; then
                log_error "--skip-stack-stop cannot be combined with --yes."
                log_error "Migrating a live stack requires an interactive operator to confirm."
                exit 1
            fi
            ;;
        resume|status|abort|verify)
            ;;
        *)
            log_error "Unknown subcommand: ${_MV_SUBCOMMAND}"
            _mv_usage
            exit 1
            ;;
    esac

    local _mv_seen_option
    for _mv_seen_option in "${_mv_seen_options[@]+"${_mv_seen_options[@]}"}"; do
        case "${_MV_SUBCOMMAND}:${_mv_seen_option}" in
            run:*) ;;
            resume:--dry-run|resume:--force|resume:--force-format|resume:--yes|\
            resume:--start-policy|resume:--start|resume:--no-start) ;;
            *)
                log_error "Unknown option for '${_MV_SUBCOMMAND}': ${_mv_seen_option}"
                case "${_MV_SUBCOMMAND}" in
                    status) log_error "Usage: sudo utilities/setup-storage.sh migrate status" ;;
                    abort)  log_error "Usage: sudo utilities/setup-storage.sh migrate abort" ;;
                    verify) log_error "Usage: sudo utilities/setup-storage.sh migrate verify" ;;
                    resume) log_error "Usage: sudo utilities/setup-storage.sh migrate resume [--dry-run] [--force] [--force-format] [--yes] [--start-policy MODE]" ;;
                    *)      _mv_usage ;;
                esac
                exit 2
                ;;
        esac
    done

    case "${_MV_START_POLICY}" in
        ""|auto|ask|manual) ;;
        *) log_error "Invalid --start-policy: ${_MV_START_POLICY}"; exit 1 ;;
    esac
}

_mv_resolve_args() {
    if [[ -z "${_MV_SOURCE}" ]]; then
        if [[ "${_MV_DIRECTION}" == "block-to-boot" ]]; then
            if [[ -n "${_MV_DEVICE}" ]]; then
                local _detected_src
                _detected_src="$(findmnt -n -o TARGET --source "${_MV_DEVICE}" 2>/dev/null || true)"
                [[ -n "${_detected_src}" ]] && _MV_SOURCE="${_detected_src}"
            fi
        else
            _MV_SOURCE="${PROJECT_STATE_DIR:-${_VW_DEFAULT_STATE_DIR}}"
        fi
    fi

    case "${_MV_START_POLICY}" in
        "" ) if [[ "${_MV_YES:-false}" == "true" || ! -t 0 ]]; then _MV_START_POLICY="auto"; else _MV_START_POLICY="ask"; fi ;;
        auto|ask|manual) ;;
        *) log_error "Invalid --start-policy: ${_MV_START_POLICY}"; exit 1 ;;
    esac

    _MV_SOURCE="$(_mv_realpath "${_MV_SOURCE}")"
    if [[ -n "${_MV_TARGET}" ]]; then
        _MV_TARGET="$(_mv_realpath "${_MV_TARGET}")"
    fi

    local _mv_unsafe_re=$'[^a-zA-Z0-9/._-]'
    if [[ "${_MV_SOURCE}" =~ ${_mv_unsafe_re} ]]; then
        log_error "Source path contains unsafe characters: ${_MV_SOURCE}"
        log_error "Only alphanumeric characters and / . _ - are allowed."
        exit 1
    fi
    if [[ -n "${_MV_TARGET}" && "${_MV_TARGET}" =~ ${_mv_unsafe_re} ]]; then
        log_error "Target path contains unsafe characters: ${_MV_TARGET}"
        log_error "Only alphanumeric characters and / . _ - are allowed."
        exit 1
    fi
}

_mv_device_has_no_fs_or_signatures() {
    local device="$1" fs_type wipefs_out wipefs_rc sig_count

    fs_type="$(blkid -o value -s TYPE "$device" 2>/dev/null || true)"
    [[ -z "${fs_type}" ]] || return 1

    wipefs_out="$(_storage_device_has_data_signatures "$device")"
    wipefs_rc=$?
    (( wipefs_rc == 0 )) || return 1

    sig_count="$(printf '%s\n' "$wipefs_out" \
        | grep -v '^#' \
        | grep -c '[^[:space:]]' 2>/dev/null || true)"
    (( sig_count == 0 ))
}

_mv_require_force_format_for_blank_device() {
    [[ "${_MV_DIRECTION}" == "boot-to-block" ]] || return 0
    [[ -n "${_MV_DEVICE:-}" ]] || return 0
    mountpoint -q "${_MV_TARGET}" 2>/dev/null && return 0
    [[ "${_MV_FORCE_FORMAT}" != "true" ]] || return 0
    _mv_device_has_no_fs_or_signatures "${_MV_DEVICE}" || return 0

    _mv_log error "Blank target device requires --force-format."
    _mv_log error "Formatting remains explicitly gated and is never inferred from selecting the device."
    _mv_log error "Re-run with a sudo-safe command such as:"
    _mv_log error "  sudo utilities/setup-storage.sh migrate run --device ${_MV_DEVICE} --target ${_MV_TARGET} --force-format"
    return 1
}

_mv_validate_mounted_target_identity() {
    [[ "${_MV_DIRECTION}" == "boot-to-block" && -n "${_MV_DEVICE:-}" ]] || return 0
    mountpoint -q "${_MV_TARGET}" 2>/dev/null || return 0

    if ! storage_validate_volume_identity "${_MV_TARGET}" "${_MV_DEVICE}"; then
        _mv_log error "Target ${_MV_TARGET} is already mounted but its filesystem identity is invalid."
        _mv_log error "Refusing to migrate onto a mounted filesystem identified only by path or marker filename."
        _mv_log error "Repair/adopt only after proving the disk: sudo utilities/setup-storage.sh setup --data-device ${_MV_DEVICE} --data-mount ${_MV_TARGET}"
        return 1
    fi
    _mv_log info "Mounted target filesystem identity validated: ${_MV_TARGET}"
}

_mv_step_validate() {
    _mv_log info "── validate ──────────────────────────────────────────────────────"

    require_commands rsync flock findmnt lsblk df du awk sed mktemp stat
    if [[ -n "${_MV_DEVICE}" ]]; then
        require_commands blkid mkfs.ext4
    fi

    [[ -d "${_MV_SOURCE}" ]] || {
        _mv_log error "Source path does not exist or is not a directory: ${_MV_SOURCE}"
        return 1
    }

    # block-to-boot: source must be the mounted filesystem identified by the
    # configured source device and structured volume identity marker.
    if [[ "${_MV_DIRECTION}" == "block-to-boot" ]]; then
        if [[ -z "${_MV_DEVICE}" ]]; then
            _mv_log error "block-to-boot requires the expected source block device."
            return 1
        fi
        if ! mountpoint -q "${_MV_SOURCE}" 2>/dev/null; then
            _mv_log error "block-to-boot: '${_MV_SOURCE}' is not a mounted filesystem."
            _mv_log error "Ensure the block data volume is mounted before running this migration."
            _mv_log error "  sudo mount ${_MV_SOURCE}"
            return 1
        fi
        if ! storage_validate_volume_identity "${_MV_SOURCE}" "${_MV_DEVICE}"; then
            _mv_log error "block-to-boot: source filesystem identity is invalid."
            _mv_log error "Refusing to migrate from a volume identified only by path or marker filename."
            _mv_log error "Repair only after proving the disk: sudo utilities/setup-storage.sh setup --data-device ${_MV_DEVICE}"
            return 1
        fi
    fi

    local canon_src canon_tgt
    canon_src="$(_mv_realpath "${_MV_SOURCE}")"
    canon_tgt="$(_mv_realpath "${_MV_TARGET}")"
    [[ "${canon_src}" != "${canon_tgt}" ]] || {
        _mv_log error "Source and target are the same path: ${canon_src}"
        return 1
    }

    [[ "${canon_tgt}" != "${canon_src}/"* ]] || {
        _mv_log error "Target '${canon_tgt}' is a subdirectory of source '${canon_src}'."
        _mv_log error "This would cause an rsync infinite loop. Aborted."
        return 1
    }

    if [[ "${_MV_TARGET}" == /dev/* && -z "${_MV_DEVICE}" ]]; then
        _mv_log error "--target looks like a block device path: ${_MV_TARGET}"
        _mv_log error "To migrate to a block device use --device ${_MV_TARGET} with a directory --target."
        _mv_log error "Example: --device ${_MV_TARGET} --target ${_VW_DEFAULT_DATA_MOUNT}"
        return 1
    fi

    if pgrep -x rsync >/dev/null 2>&1 \
            && find /proc/*/fd -lname "${_MV_SOURCE}/*" -print0 2>/dev/null \
               | grep -qzl ''; then
        _mv_log error "An rsync process has open file descriptors in ${_MV_SOURCE}."
        _mv_log error "Wait for it to finish before migrating."
        return 1
    fi

    if [[ -n "${_MV_DEVICE}" ]]; then
        [[ -b "${_MV_DEVICE}" ]] || {
            _mv_log error "'${_MV_DEVICE}' is not a valid block device."
            _mv_log error "Verify the device is attached: lsblk | grep ${_MV_DEVICE##*/}"
            _mv_log error "If the device path looks wrong, this may be a script bug — please"
            _mv_log error "report it. As a workaround, pass the device explicitly: --device /dev/sda"
            return 1
        }
        local dev_mount
        dev_mount="$(findmnt -n -o TARGET --source "${_MV_DEVICE}" 2>/dev/null || true)"
        # For boot-to-block: the target device must not already be mounted elsewhere.
        # For block-to-boot: the device is the source mount — being mounted is expected.
        if [[ "${_MV_DIRECTION}" == "boot-to-block" ]]; then
            if [[ -n "${dev_mount}" && "${dev_mount}" != "${_MV_TARGET}" ]]; then
                _mv_log error "Device ${_MV_DEVICE} is already mounted at: ${dev_mount}"
                _mv_log error "Unmount it first or omit --device if the target is already mounted."
                return 1
            fi
            _mv_validate_mounted_target_identity || return 1
            _mv_require_force_format_for_blank_device || return 1
        fi
    fi

    # Disk-space check: for block-to-boot and dir-to-dir, run now.
    # For boot-to-block with a new device, defer until after format and mount.
    if [[ "${_MV_DIRECTION}" == "block-to-boot" ]] || [[ -z "${_MV_DEVICE}" ]]; then
        mkdir -p "${_MV_TARGET}" 2>/dev/null || true
        _mv_check_disk_space "${_MV_SOURCE}" "${_MV_TARGET}"
    else
        _mv_log info "Block-device migration: disk space check deferred until after format and mount."
    fi

    _mv_check_stale_backup

    if [[ "${_MV_SKIP_STACK_STOP}" == "true" ]]; then
        local running_containers
        running_containers="$(docker compose ps --status running --quiet 2>/dev/null \
            | wc -l | tr -d ' ' || true)"
        if (( running_containers > 0 )); then
            if [[ "${DRY_RUN}" == "true" ]]; then
                _mv_log info "[DRY RUN] would: require interactive 'LIVE' confirmation (live stack detected)"
            else
                _mv_log warn "WARNING: ${running_containers} VaultWarden container(s) are currently running."
                _mv_log warn "Migrating a live stack risks SQLite WAL corruption."
                _mv_log warn "Data integrity cannot be guaranteed if the database is actively written."
                _mv_confirm_by_typing \
                    "You are about to migrate a LIVE stack." \
                    "LIVE"
            fi
        fi
    fi

    [[ -f "${PROJECT_ROOT}/.env" ]] || {
        _mv_log error ".env not found at: ${PROJECT_ROOT}/.env"
        return 1
    }
    grep -q "^PROJECT_STATE_DIR=" "${PROJECT_ROOT}/.env" 2>/dev/null || {
        _mv_log error "PROJECT_STATE_DIR key not found in .env"
        return 1
    }

    [[ -f "${PROJECT_ROOT}/docker-compose.yml" ]] || {
        _mv_log error "docker-compose.yml not found at: ${PROJECT_ROOT}/docker-compose.yml"
        return 1
    }

    if [[ "${DRY_RUN}" != "true" ]]; then
        _mv_state_write MV_SOURCE           "${_MV_SOURCE}"
        _mv_state_write MV_TARGET           "${_MV_TARGET}"
        _mv_state_write MV_DEVICE           "${_MV_DEVICE:-none}"
        _mv_state_write MV_DIRECTION        "${_MV_DIRECTION}"
        _mv_state_write MV_START_TS         "$(date +%s)"
        _mv_state_write MV_LOG_FILE         "${_MV_LOG_FILE}"
        _mv_state_write MV_SKIP_STACK_STOP  "${_MV_SKIP_STACK_STOP}"
        _mv_state_write MV_DELETE_SOURCE    "${_MV_DELETE_SOURCE}"
        _mv_state_write MV_FORCE_FORMAT     "${_MV_FORCE_FORMAT}"
    fi

    _mv_log success "Pre-flight validation passed."
}

_mv_step_backup_prompt() {
    _mv_log info "── backup_prompt ─────────────────────────────────────────────────"

    if [[ "${_MV_FORCE}" == "true" ]]; then
        _mv_log info "Skipping backup prompt (--force)."
        return 0
    fi

    _mv_log warn "⚠  Before migrating, a current backup is strongly recommended."
    _mv_log warn "   Run: sudo ./backup.sh full"
    _mv_log warn "   Once complete, re-run this migration with --force to skip this prompt."

    _mv_confirm "Confirm you have a recent backup and wish to proceed."
}

_mv_step_stop() {
    _mv_log info "── stop ──────────────────────────────────────────────────────────"

    if [[ "${_MV_SKIP_STACK_STOP}" == "true" ]]; then
        _mv_log warn "Skipping stack stop (--skip-stack-stop). Proceeding with live stack."
    else
        _mv_log info "Container state before stop:"
        docker compose ps --format json 2>/dev/null || true

        if [[ "${DRY_RUN}" == "true" ]]; then
            _mv_log info "[DRY RUN] would: stop VaultWarden stack (stop_services)"
            return 0
        fi

        stop_services   # from lib/docker.sh

        _mv_log info "Container state after stop:"
        docker compose ps --format json 2>/dev/null || true
        _mv_log success "Stack stopped."
    fi

    [[ "${DRY_RUN}" == "true" ]] && return 0
    local wal_files
    wal_files="$(find "${_MV_SOURCE}" -name "*.sqlite3-wal" -size +0c -type f 2>/dev/null || true)"
    if [[ -n "${wal_files}" ]]; then
        _mv_log warn "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        _mv_log warn "  ⚠  WAL WARNING: Non-empty SQLite WAL file(s) found after stack stop:"
        local _wal
        while IFS= read -r _wal; do
            _mv_log warn "    ${_wal}"
        done <<< "${wal_files}"
        _mv_log warn "  A non-empty WAL indicates the database was not cleanly checkpointed."
        _mv_log warn "  WAL/SHM files are excluded from rsync; copying without them may"
        _mv_log warn "  leave the target database in an inconsistent state."
        _mv_log warn "  Remediation before proceeding:"
        _mv_log warn "    sudo sqlite3 <path/to/db.sqlite3> 'PRAGMA wal_checkpoint(FULL);'"
        _mv_log warn "  Or run: sudo ./maintenance.sh db-maint"
        _mv_log warn "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        _mv_confirm "Non-empty WAL file(s) detected. Proceeding risks an inconsistent database migration. Confirm to continue."
    fi
}

_mv_step_format() {
    _mv_log info "── format ────────────────────────────────────────────────────────"

    if [[ "${_MV_DIRECTION}" == "block-to-boot" ]]; then
        _mv_log info "block-to-boot migration: no format step required — skipping."
        return 0
    fi

    if [[ -z "${_MV_DEVICE}" ]]; then
        _mv_log info "No --device supplied — skipping format step (directory-to-directory migration)."
        return 0
    fi

    if mountpoint -q "${_MV_TARGET}" 2>/dev/null; then
        _mv_validate_mounted_target_identity || return 1
        _mv_log info "Target ${_MV_TARGET} is already mounted with a valid filesystem identity — skipping format."
        _mv_check_disk_space "${_MV_SOURCE}" "${_MV_TARGET}"
        return 0
    fi

    if [[ "${DRY_RUN}" == "true" ]]; then
        _mv_log info "[DRY RUN] would: setup_data_volume (format and mount ${_MV_DEVICE} at ${_MV_TARGET})"
        return 0
    fi

    DATA_VOLUME_DEVICE="${_MV_DEVICE}"
    DATA_VOLUME_MOUNT="${_MV_TARGET}"
    export DATA_VOLUME_DEVICE DATA_VOLUME_MOUNT
    if [[ "${_MV_FORCE_FORMAT}" == "true" ]]; then
        DATA_VOLUME_FORCE_FORMAT=true
        export DATA_VOLUME_FORCE_FORMAT
    fi

    setup_data_volume   # from lib/storage.sh
    _mv_log success "Target volume formatted and mounted: ${_MV_DEVICE} → ${_MV_TARGET}"

    _mv_check_disk_space "${_MV_SOURCE}" "${_MV_TARGET}"
}

_mv_step_rsync() {
    _mv_log info "── rsync ─────────────────────────────────────────────────────────"

    local -a rsync_flags=(
        --archive
        --hard-links
        --acls
        --xattrs
        --sparse
        --one-file-system
        --delete
        --delete-excluded
        --human-readable
        --progress
        --stats
    )

    _mv_ensure_stack_stopped_for_rsync
    _mv_add_rsync_filters rsync_flags

    [[ "${DRY_RUN}" == "true" ]] && rsync_flags+=(--dry-run)

    if [[ "${DRY_RUN}" != "true" ]]; then
        mkdir -p "${_MV_TARGET}"
    else
        _mv_log info "[DRY RUN] would: mkdir -p ${_MV_TARGET}"
    fi

    _mv_log info "Running rsync: ${_MV_SOURCE%/}/ → ${_MV_TARGET}"
    _mv_log info "Flags: ${rsync_flags[*]}"

    local rsync_rc=0
    rsync "${rsync_flags[@]}" "${_MV_SOURCE%/}/" "${_MV_TARGET}" || rsync_rc=$?

    if (( rsync_rc != 0 )); then
        _mv_log error "rsync failed with exit code ${rsync_rc}. Investigate the output above."
        _mv_log error "Resume the migration once resolved: sudo utilities/setup-storage.sh migrate resume"
        return 1
    fi

    _mv_log success "rsync transfer complete."
}

_mv_step_verify() {
    _mv_log info "── verify ────────────────────────────────────────────────────────"

    if [[ "${DRY_RUN}" == "true" ]]; then
        _mv_log info "[DRY RUN] would: verify included files with rsync --checksum --dry-run"
        _mv_log info "[DRY RUN] would: report informational byte counts"
        return 0
    fi

    local src_bytes tgt_bytes delta pct_x100

    src_bytes="$(_mv_du_bytes "${_MV_SOURCE}/")"
    tgt_bytes="$(_mv_du_bytes "${_MV_TARGET}/")"

    _mv_log info "Source size : $(_mv_fmt_bytes "${src_bytes}")"
    _mv_log info "Target size : $(_mv_fmt_bytes "${tgt_bytes}")"

    if (( src_bytes == 0 )); then
        _mv_log warn "Source reports 0 bytes — skipping percentage check."
        return 0
    fi

    # Compute absolute delta as a percentage of source, scaled by 100 for precision.
    delta=$(( tgt_bytes > src_bytes ? tgt_bytes - src_bytes : src_bytes - tgt_bytes ))
    pct_x100=$(( delta * 10000 / src_bytes ))

    _mv_log info "Delta: $(_mv_fmt_bytes "${delta}") ($(( pct_x100 / 100 )).$(( pct_x100 % 100 ))%)"

    if (( pct_x100 > _MV_VERIFY_TOLERANCE_PCT * 100 )); then
        _mv_log warn "Byte-count delta exceeds ${_MV_VERIFY_TOLERANCE_PCT}% tolerance; treating as informational."
        _mv_log warn "Included-file verification below is authoritative because migration intentionally excludes/protects runtime artifacts."
    else
        _mv_log success "Byte-count informational check passed (delta ≤ ${_MV_VERIFY_TOLERANCE_PCT}%)."
    fi

    # Included-file integrity check: rsync --checksum --dry-run reports any
    # remaining included-file content, metadata, or deletion differences while
    # honoring the same exclude/protect filters used by the transfer.
    _mv_log info "Running included-file integrity check (rsync --checksum --dry-run)..."
    local _chk_out _chk_count
    # Pass the same excludes used during transfer so intentionally excluded
    # files (WAL, PID, sock) do not generate false-positive >f mismatches.
    local -a _chk_flags=(--archive --checksum --dry-run --itemize-changes --delete --delete-excluded)
    _mv_add_rsync_filters _chk_flags
    _chk_out="$(rsync "${_chk_flags[@]}" \
        "${_MV_SOURCE%/}/" "${_MV_TARGET}" 2>/dev/null || true)"
    _chk_count="$(printf '%s\n' "${_chk_out}" | awk 'NF && $1 !~ /^\.d/ { count++ } END { print count + 0 }')"

    if (( _chk_count > 0 )); then
        _mv_log error "Included-file verification FAILED: ${_chk_count} rsync change(s) remain."
        _mv_log error "Items with discrepancies:"
        printf '%s\n' "${_chk_out}" | awk 'NF && $1 !~ /^\.d/ { $1=""; sub(/^ /, ""); print }' | \
            while IFS= read -r _f; do _mv_log error "  ${_f}"; done
        _mv_log error "Investigate before proceeding. Resume with: sudo utilities/setup-storage.sh migrate resume"
        return 1
    fi

    _mv_log success "Included-file verification passed (rsync dry-run reports no remaining included-file changes)."
}

_mv_step_rename_source() {
    _mv_log info "── rename_source ──────────────────────────────────────────────────"

    local renamed="${_MV_SOURCE}.pre-migration.${_MV_RUN_TIMESTAMP}"

    if mountpoint -q "${_MV_SOURCE}" 2>/dev/null; then
        if [[ "${_MV_DIRECTION}" == "block-to-boot" ]]; then
            # Source is the block volume mount root — renaming it is not possible.
            # Best practice: skip rename and emit a clear warning instead.
            _mv_log warn "Source '${_MV_SOURCE}' is the block volume mount root — rename skipped."
            _mv_log warn "After verifying the migration and rebooting, you can safely unmount"
            _mv_log warn "and detach the data disk:"
            _mv_log warn "  sudo umount ${_MV_SOURCE}"
        else
            _mv_log warn "Source ${_MV_SOURCE} is a mount point — rename not meaningful."
            _mv_log warn "After verifying the migration, unmount and detach the old volume manually."
        fi
        return 0
    fi

    if [[ "${DRY_RUN}" == "true" ]]; then
        _mv_log info "[DRY RUN] would: mv ${_MV_SOURCE} ${renamed}"
    else
        mv "${_MV_SOURCE}" "${renamed}"
        _mv_log success "Source renamed: ${_MV_SOURCE} → ${renamed}"
    fi
}

_mv_step_delete_source() {
    _mv_log info "── delete_source ─────────────────────────────────────────────────"

    local _nullglob_was_off=false
    shopt -q nullglob || _nullglob_was_off=true
    shopt -s nullglob

    local candidate newest_ts=0 candidate_ts cand_renamed=""
    for candidate in "${_MV_SOURCE}.pre-migration."*/; do
        [[ -d "${candidate}" ]] || continue
        candidate_ts="$(stat -c '%Y' "${candidate}" 2>/dev/null || echo 0)"
        if (( candidate_ts > newest_ts )); then
            newest_ts="${candidate_ts}"
            cand_renamed="${candidate%/}"
        fi
    done

    [[ "${_nullglob_was_off}" == "true" ]] && shopt -u nullglob

    local renamed="${cand_renamed}"

    if [[ -z "${renamed}" || ! -d "${renamed}" ]]; then
        _mv_log warn "Renamed source not found — nothing to delete."
        return 0
    fi

    _mv_log warn "You are about to permanently delete:"
    _mv_log warn "  ${renamed}"
    _mv_confirm_by_typing \
        "To confirm deletion, type the FULL PATH shown above." \
        "${renamed}"

    if [[ "${DRY_RUN}" == "true" ]]; then
        _mv_log info "[DRY RUN] would: rm -rf ${renamed}"
    else
        rm -rf "${renamed}"
        _mv_log success "Source deleted: ${renamed}"
    fi
}

_mv_prune_env_backups() {
    # Prune older .env.pre-migration.* backups — keep only the newest one.
    local env_file="${PROJECT_ROOT}/.env"
    local _env_cand _env_newest _env_newest_ts=0 _env_cand_ts
    local -a _env_all_cands=()
    _env_newest="${env_file}.pre-migration.${_MV_RUN_TIMESTAMP}"
    for _env_cand in "${PROJECT_ROOT}"/.env.pre-migration.*; do
        [[ -f "${_env_cand}" ]] || continue
        _env_all_cands+=( "${_env_cand}" )
        _env_cand_ts="$(stat -c '%Y' "${_env_cand}" 2>/dev/null || echo 0)"
        if (( _env_cand_ts > _env_newest_ts )); then
            _env_newest_ts="${_env_cand_ts}"
            _env_newest="${_env_cand}"
        fi
    done
    for _env_cand in "${_env_all_cands[@]+"${_env_all_cands[@]}"}"; do
        [[ "${_env_cand}" == "${_env_newest}" ]] && continue
        rm -f "${_env_cand}"
        _mv_log info "Removed stale .env backup: ${_env_cand}"
    done
}

_mv_step_update_env() {
    _mv_log info "── update_env ────────────────────────────────────────────────────"

    local env_file="${PROJECT_ROOT}/.env"
    local old_state_dir="${_MV_SOURCE}"

    if [[ "${DRY_RUN}" != "true" ]]; then
        cp "${env_file}" "${env_file}.pre-migration.${_MV_RUN_TIMESTAMP}"
        chmod 0600 "${env_file}.pre-migration.${_MV_RUN_TIMESTAMP}"
        _mv_log info ".env backup created: ${env_file}.pre-migration.${_MV_RUN_TIMESTAMP}"
        _mv_prune_env_backups
    else
        _mv_log info "[DRY RUN] would: cp ${env_file} ${env_file}.pre-migration.${_MV_RUN_TIMESTAMP}"
    fi

    _mv_set_env_var PROJECT_STATE_DIR "${_MV_TARGET}"

    if [[ "${_MV_DIRECTION}" == "block-to-boot" ]]; then
        # Transitioning back to boot-only mode: clear the block device binding.
        _mv_set_env_var DATA_VOLUME_MOUNT  "${_MV_TARGET}"
        _mv_set_env_var DATA_VOLUME_DEVICE ""
    elif [[ -n "${_MV_DEVICE}" ]]; then
        _mv_set_env_var DATA_VOLUME_MOUNT  "${_MV_TARGET}"
        _mv_set_env_var DATA_VOLUME_DEVICE "${_MV_DEVICE}"
    fi

    local current_backup_dir
    current_backup_dir="$(grep "^BACKUP_DIR=" "${env_file}" 2>/dev/null | cut -d= -f2- || true)"

    if [[ "${current_backup_dir}" == "${old_state_dir}/backups" ]]; then
        _mv_set_env_var BACKUP_DIR "${_MV_TARGET}/backups"
    elif [[ -z "${current_backup_dir}" ]]; then
        _mv_log warn "BACKUP_DIR is not set in .env."
        _mv_log warn "The runtime default will resolve via PROJECT_STATE_DIR, which has been updated to: ${_MV_TARGET}"
        _mv_log warn "Verify backup.sh behaviour post-migration to confirm backups land in the expected location."
    elif [[ "${current_backup_dir}" == "${_MV_TARGET}/backups" ]]; then
        _mv_log info "BACKUP_DIR already points to the new target — no update needed."
    else
        _mv_log warn "BACKUP_DIR is set to a custom path: ${current_backup_dir}"
        _mv_log warn "This path was NOT auto-updated. Verify it points to the correct location on the new volume."
        _mv_log warn "Update manually if needed: nano ${env_file}"
        if [[ "${_MV_YES:-false}" == "true" ]]; then
            _mv_log warn "Non-interactive mode (--yes): BACKUP_DIR confirmation bypassed. Verify manually post-migration."
            _MV_BACKUP_DIR_CUSTOM_WARNING="${current_backup_dir}"
        else
            _mv_confirm "Acknowledge: BACKUP_DIR (${current_backup_dir}) was not updated and requires manual verification."
        fi
    fi

    _mv_log success ".env updated for new state directory: ${_MV_TARGET}"
}


_mv_step_sync_runtime_env() {
    _mv_log info "── sync_runtime_env ──────────────────────────────────────────────"

    if [[ "${DRY_RUN}" == "true" ]]; then
        _mv_log info "[DRY RUN] would: regenerate ${_MV_TARGET}/config/install.env and /etc/vaultwarden/vaultwarden.env from repo .env"
        return 0
    fi

    VW_ENV_EDIT_ALLOW_MIGRATION_SYNC=true "${PROJECT_ROOT}/utilities/env-edit.sh" sync || return 1
    fix_known_path_permissions "${_MV_TARGET}/config"
    fix_known_path_permissions "${_MV_TARGET}/config/install.env"
    fix_known_path_permissions "/etc/vaultwarden"
    fix_known_path_permissions "/etc/vaultwarden/vaultwarden.env"
    _mv_log success "Runtime env regenerated for migrated PROJECT_STATE_DIR: ${_MV_TARGET}"
}

_mv_step_update_dropin() {
    _mv_log info "── update_dropin ─────────────────────────────────────────────────"

    if [[ "${DRY_RUN}" == "true" ]]; then
        _mv_log info "[DRY RUN] would: run utilities/setup-systemd.sh install to regenerate current ReadWritePaths drop-ins"
        return 0
    fi

    _mv_log info "Regenerating systemd drop-ins from canonical runtime env..."
    if VW_ENV_EDIT_ALLOW_MIGRATION_SYNC=true "${PROJECT_ROOT}/utilities/setup-systemd.sh" install; then
        _mv_log success "Systemd drop-ins regenerated for data path: ${_MV_TARGET}"
    else
        _mv_log warn "utilities/setup-systemd.sh install did not complete successfully."
        _mv_log warn "Run manually after migration: sudo ./setup.sh systemd install"
        return 1
    fi
}

_mv_step_mount_guard() {
    _mv_log info "── mount_guard ───────────────────────────────────────────────────"

    if [[ -z "${_MV_DEVICE}" ]]; then
        _mv_log info "No --device supplied — skipping Docker mount guard installation."
        return 0
    fi

    if [[ "${DRY_RUN}" == "true" ]]; then
        _mv_log info "[DRY RUN] would: install_docker_mount_guard for ${_MV_TARGET}"
        return 0
    fi

    DATA_VOLUME_DEVICE="${_MV_DEVICE}"
    DATA_VOLUME_MOUNT="${_MV_TARGET}"
    export DATA_VOLUME_DEVICE DATA_VOLUME_MOUNT

    install_docker_mount_guard   # from lib/storage.sh
    _mv_log success "Docker mount guard installed."
}

_mv_step_start() {
    _mv_log info "── start ─────────────────────────────────────────────────────────"

    if [[ "${DRY_RUN}" == "true" ]]; then
        _mv_log info "[DRY RUN] would: start VaultWarden stack (start_services)"
        return 0
    fi
    case "${_MV_START_POLICY:-auto}" in
        manual)
            _mv_log warn "Start policy manual: not starting VaultWarden stack after migration."
            _mv_log info "Manual command: sudo ./startup.sh"
            return 0
            ;;
        ask)
            local _answer
            read -r -p "Start VaultWarden stack now on the migrated storage? [yes/no] (default: yes): " _answer
            case "$_answer" in
                n|N|no|NO)
                    _mv_log warn "Operator chose not to start VaultWarden stack after migration."
                    _mv_log info "Manual command: sudo ./startup.sh"
                    _MV_START_POLICY="manual"
                    return 0
                    ;;
            esac
            ;;
    esac

    if ! start_services; then   # from lib/docker.sh
        _mv_log error "start_services failed — health check will surface the failure explicitly."
    else
        _mv_log success "Stack started."
    fi
}

_mv_step_healthcheck() {
    _mv_log info "── healthcheck ───────────────────────────────────────────────────"

    if [[ "${DRY_RUN}" == "true" ]]; then
        _mv_log info "[DRY RUN] would: poll 'docker compose ps --status running --quiet' for healthy state (up to 120s)"
        _mv_log info "[DRY RUN] would: write MIGRATION_COMPLETE=true to state file"
        _mv_print_checklist
        return 0
    fi
    if [[ "${_MV_START_POLICY:-auto}" == "manual" ]]; then
        _mv_log warn "Start policy manual: skipping post-migration health check because services were not started."
        _mv_print_checklist
        return 0
    fi

    _mv_log info "Waiting for vaultwarden container to become healthy (up to 120s)..."
    local _dw_rc=0
    docker_wait_healthy vaultwarden_app 120 10 || _dw_rc=$?

    if (( _dw_rc == 0 )); then
        local _cid _rcount
        while IFS= read -r _cid; do
            [[ -z "${_cid}" ]] && continue
            _rcount="$(docker inspect --format '{{.RestartCount}}' "${_cid}" 2>/dev/null || echo 0)"
            if (( _rcount > 0 )); then
                _mv_log warn "Container ${_cid} has RestartCount=${_rcount} — may be crash-looping."
                _mv_log warn "  Check logs: docker logs ${_cid}"
            fi
        done < <(docker compose ps --quiet 2>/dev/null)

        local _rocket_port="${ROCKET_PORT:-8080}"
        local _http_healthy=false _http_try=0 _http_max=6
        _mv_log info "HTTP health probe: http://localhost:${_rocket_port}/alive (up to 60s)"
        while (( _http_try < _http_max )); do
            if curl -sf --max-time 5 "http://localhost:${_rocket_port}/alive" >/dev/null 2>&1; then
                _http_healthy=true
                break
            fi
            (( _http_try++ )) || true
            _mv_log info "  Waiting for HTTP health... (attempt ${_http_try}/${_http_max})"
            sleep 10
        done
        if [[ "${_http_healthy}" == "true" ]]; then
            _mv_log success "HTTP health probe passed: /alive responded successfully."
            _mv_state_write MIGRATION_COMPLETE "true"
            _mv_log success "All containers are running. Migration complete."
            _mv_warn_fstab_entries
            _mv_print_checklist
        else
            _mv_log error "HTTP health probe failed after $(( _http_try * 10 ))s."
            _mv_log error "Containers are running but /alive did not respond on port ${_rocket_port}."
            _mv_log error "Verify manually: curl -v http://localhost:${_rocket_port}/alive"
            _mv_log error "Check logs:      docker compose logs vaultwarden"
            _mv_log error "MIGRATION_COMPLETE not written. Fix the issue then resume or abort."
            return 1
        fi
    else
        _mv_log error "Health check timed out or container exited (docker_wait_healthy returned ${_dw_rc})."
        _mv_log error "Current container state:"
        docker compose ps 2>/dev/null || true
        _mv_log error "Recent logs:"
        docker compose logs --tail=50 2>/dev/null || true
        _mv_log error "MIGRATION_COMPLETE not written. Investigate and resume or abort."
        return 1
    fi
}

_mv_print_checklist() {
    local renamed_src="${_MV_SOURCE}.pre-migration.<original-run-timestamp>"
    if [[ "${DRY_RUN}" != "true" ]]; then
        renamed_src="${_MV_SOURCE}.pre-migration.${_MV_RUN_TIMESTAMP}"
    fi
    printf '\n'
    printf '═══════════════════════════════════════════════════════════════\n'
    printf '  Post-Migration Checklist\n'
    printf '═══════════════════════════════════════════════════════════════\n'
    printf '  1. Log in to VaultWarden and verify your vault data is intact.\n'
    printf '  2. Run: docker compose ps  — confirm all services are '\''healthy'\''.\n'
    printf '  3. Run: systemctl status vaultwarden-startup  — confirm unit loads cleanly.\n'
    printf '  4. Run: sudo ./setup.sh systemd install\n'
    printf '     This installs systemd service drop-ins for the new data path\n'
    printf '     so automated backups, health checks, and maintenance can write\n'
    printf '     to the new volume under ProtectSystem=strict.\n'
    printf '  5. Test a scheduled backup: sudo ./backup.sh run full\n'
    printf '  6. Verify backup path uses new volume: check BACKUP_DIR in .env\n'
    printf '     If BACKUP_DIR was a custom path it was NOT auto-updated — verify manually.\n'
    printf '  7. After a satisfying reboot test, remove the renamed source:\n'
    printf '       sudo rm -rf '\''%s'\''\n' "${renamed_src}"
    printf '  8. (If you added custom services to docker-compose.yml with hardcoded\n'
    printf '     paths) Verify: docker compose config | grep '\''%s'\''\n' "${_MV_SOURCE}"
    printf '     Any remaining references must be updated manually.\n'
    if [[ -n "${_MV_BACKUP_DIR_CUSTOM_WARNING:-}" ]]; then
        printf '  ─────────────────────────────────────────────────────────────────\n'
        printf '  ⚠  ACTION REQUIRED: --yes mode bypassed the BACKUP_DIR confirmation.\n'
        printf '     Custom BACKUP_DIR: %s\n' "${_MV_BACKUP_DIR_CUSTOM_WARNING}"
        printf '     This path was NOT auto-updated. Verify it points to the correct\n'
        printf '     location on the new volume and update .env if needed:\n'
        printf '       nano %s/.env\n' "${PROJECT_ROOT}"
    fi
    printf '═══════════════════════════════════════════════════════════════\n'
    printf '  Migration log: %s\n' "${_MV_LOG_FILE}"
    printf '  .env backup:   %s.pre-migration.%s\n' "${PROJECT_ROOT}/.env" "${_MV_RUN_TIMESTAMP}"
    printf '═══════════════════════════════════════════════════════════════\n'
    printf '\n'
}

_mv_print_status() {
    if [[ ! -f "${_MV_STATE_FILE}" ]]; then
        log_info "No migration in progress or previously recorded."
        return 0
    fi

    local src tgt device direction start_ts complete

    src="$(_mv_state_read MV_SOURCE)"
    tgt="$(_mv_state_read MV_TARGET)"
    device="$(_mv_state_read MV_DEVICE)"
    direction="$(_mv_state_read MV_DIRECTION)"
    start_ts="$(_mv_state_read MV_START_TS)"
    complete="$(_mv_state_read MIGRATION_COMPLETE)"

    printf '\n'
    printf '  Migration State\n'
    printf '  ───────────────────────────────────────────────\n'
    printf '  %-20s %s\n' "Direction:" "${direction:-boot-to-block}"
    printf '  %-20s %s\n' "Source:"   "${src:-unknown}"
    printf '  %-20s %s\n' "Target:"   "${tgt:-unknown}"
    printf '  %-20s %s\n' "Device:"   "${device:-none}"
    printf '  %-20s %s\n' "Format blank:" "$([[ "$(_mv_state_read MV_FORCE_FORMAT)" == "true" ]] && echo yes || echo no)"
    printf '  %-20s %s\n' "Started:"  \
        "$(date -d "@${start_ts}" '+%Y-%m-%d %H:%M:%S' 2>/dev/null || printf '%s' "${start_ts}")"
    printf '  %-20s %s\n' "Complete:" "${complete:-no}"
    printf '  ───────────────────────────────────────────────\n'
    printf '\n'

    local -a steps=(
        "STEP_VALIDATE_DONE:Validate pre-flight"
        "STEP_BACKUP_DONE:Backup confirmation"
        "STEP_STOP_DONE:Stop stack"
        "STEP_FORMAT_DONE:Format/mount volume"
        "STEP_RSYNC_DONE:rsync transfer"
        "STEP_VERIFY_DONE:Verify byte count"
        "STEP_SOURCE_RENAMED_DONE:Rename source"
        "STEP_SOURCE_DELETED_DONE:Delete source"
        "STEP_ENV_UPDATED_DONE:Update .env"
        "STEP_DROPIN_UPDATED_DONE:Update systemd drop-ins"
        "STEP_MOUNT_GUARD_DONE:Docker mount guard"
        "STEP_START_DONE:Start stack"
        "STEP_HEALTHCHECK_DONE:Health check"
    )

    local step token label status_str
    for step in "${steps[@]}"; do
        token="${step%%:*}"
        label="${step##*:}"
        if _mv_state_has "${token}"; then
            status_str="✓ done"
        else
            status_str="  pending"
        fi
        printf '  %-14s  %s\n' "${status_str}" "${label}"
    done
    printf '\n'

    if [[ "${complete}" == "true" ]]; then
        log_success "Migration completed successfully."
    else
        log_warn "Migration is incomplete. Resume with:"
        log_warn "  sudo utilities/setup-storage.sh migrate resume"
    fi
}

_mv_do_abort() {
    if [[ ! -f "${_MV_STATE_FILE}" ]]; then
        log_info "No migration state found. Nothing to abort."
        return 0
    fi

    local src complete
    src="$(_mv_state_read MV_SOURCE)"
    complete="$(_mv_state_read MIGRATION_COMPLETE)"

    if [[ "${complete}" == "true" ]]; then
        log_warn "Migration is already marked COMPLETE."
        _mv_confirm "Abort a completed migration? This will attempt to restore the old state."
    fi

    log_warn "Aborting migration. Attempting rollback in reverse order..."

    if _mv_state_has STEP_FORMAT_DONE && ! _mv_state_has STEP_RSYNC_DONE; then
        log_warn "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        log_warn "  ⚠  DATA NOTICE: Block device was formatted but rsync did not complete."
        log_warn "     Device : $(_mv_state_read MV_DEVICE)"
        log_warn "     Mount  : $(_mv_state_read MV_TARGET)"
        log_warn "  The new volume is formatted but empty. Source data is intact."
        log_warn "  On retry, format will be skipped (mountpoint returns true)."
        log_warn "  rsync will run from the beginning — this is safe."
        log_warn "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    fi

    if _mv_state_has STEP_START_DONE; then
        log_info "Rollback: stopping stack..."
        stop_services || log_warn "stop_services failed — continuing rollback."
    fi

    if _mv_state_has STEP_ENV_UPDATED_DONE; then
        local env_backup env_cand env_newest_ts=0 env_cand_ts
        env_backup=""
        for env_cand in "${PROJECT_ROOT}"/.env.pre-migration.*; do
            [[ -f "${env_cand}" ]] || continue
            env_cand_ts="$(stat -c '%Y' "${env_cand}" 2>/dev/null || echo 0)"
            if (( env_cand_ts > env_newest_ts )); then
                env_newest_ts="${env_cand_ts}"
                env_backup="${env_cand}"
            fi
        done
        if [[ -n "${env_backup}" && -f "${env_backup}" ]]; then
            cp "${env_backup}" "${PROJECT_ROOT}/.env"
            chmod 0600 "${PROJECT_ROOT}/.env"
            log_success ".env restored from: ${env_backup}"
            load_env_file "${PROJECT_ROOT}/.env"
        else
            log_warn ".env backup not found — manual restoration required."
            log_warn "Keys changed: PROJECT_STATE_DIR, DATA_VOLUME_MOUNT, DATA_VOLUME_DEVICE, BACKUP_DIR"
        fi
    fi

    if _mv_state_has STEP_SOURCE_RENAMED_DONE; then
        local renamed src_cand src_newest_ts=0 src_cand_ts
        renamed=""

        local _abort_nullglob_off=false
        shopt -q nullglob || _abort_nullglob_off=true
        shopt -s nullglob

        for src_cand in "${src}.pre-migration."*/; do
            [[ -d "${src_cand}" ]] || continue
            src_cand_ts="$(stat -c '%Y' "${src_cand}" 2>/dev/null || echo 0)"
            if (( src_cand_ts > src_newest_ts )); then
                src_newest_ts="${src_cand_ts}"
                renamed="${src_cand%/}"
            fi
        done

        [[ "${_abort_nullglob_off}" == "true" ]] && shopt -u nullglob

        if [[ -n "${renamed}" && -d "${renamed}" ]]; then
            if [[ ! -e "${src}" ]]; then
                mv "${renamed}" "${src}"
                log_success "Source restored: ${renamed} → ${src}"
            else
                log_warn "Cannot restore: ${src} already exists."
                log_warn "Renamed source is at: ${renamed}"
            fi
        else
            log_warn "Renamed source not found — data on target is the only copy."
        fi
    fi

    if _mv_state_has STEP_DROPIN_UPDATED_DONE; then
        local _abort_src _abort_tgt
        _abort_src="$(_mv_state_read MV_SOURCE)"
        _abort_tgt="$(_mv_state_read MV_TARGET)"
        if [[ -n "${_abort_src}" && -n "${_abort_tgt}" ]]; then
            log_info "Rollback: reversing systemd drop-in paths (${_abort_tgt} → ${_abort_src})..."
            _mv_apply_dropin_paths "${_abort_tgt}" "${_abort_src}"
        else
            log_warn "State file missing MV_SOURCE/MV_TARGET — drop-ins not reversed."
            log_warn "To restore them manually, re-run: sudo ./setup.sh systemd"
            systemctl daemon-reload || true
        fi
    fi

    log_info "Rollback: attempting to start stack from restored source..."
    start_services || log_warn "start_services failed — check manually: docker compose up -d"

    _mv_warn_fstab_entries

    if _mv_state_has STEP_FORMAT_DONE; then
        local _abort_tgt
        _abort_tgt="$(_mv_state_read MV_TARGET)"
        if [[ -n "${_abort_tgt}" ]] && mountpoint -q "${_abort_tgt}" 2>/dev/null; then
            log_warn "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
            log_warn "  ⚠  MOUNT: The new block volume remains mounted at: ${_abort_tgt}"
            log_warn "  On a true abort this may be unexpected."
            log_warn "  On retry, format will be skipped and rsync will run from scratch."
            log_warn "  To unmount: sudo umount ${_abort_tgt}"
            log_warn "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
            local _umount_reply
            read -r -t 300 -p "  Unmount ${_abort_tgt} now? [yes/no] (default: no): " _umount_reply || _umount_reply="no"
            if [[ "${_umount_reply,,}" =~ ^y(es)?$ ]]; then
                if umount "${_abort_tgt}"; then
                    log_success "Unmounted ${_abort_tgt}."
                else
                    log_warn "umount failed — unmount manually: sudo umount ${_abort_tgt}"
                fi
            else
                log_info "Leaving ${_abort_tgt} mounted. Unmount manually when ready."
            fi
        fi
    fi

    _mv_state_clear
    log_success "State file cleared."
    log_warn "Review the rollback above carefully. Some steps may require manual intervention."
    log_warn "Check: docker compose ps"
}

_mv_run_step() {
    local token="$1" fn="$2"
    if _mv_state_has "${token}"; then
        _mv_log info "Skipping (already done): ${fn#_mv_step_}"
        return 0
    fi
    _MV_CURRENT_STEP="${fn#_mv_step_}"
    operation_set_phase "${_MV_CURRENT_STEP}" "Storage migration: ${_MV_CURRENT_STEP//_/ }" 2>/dev/null || true
    "${fn}"
    _MV_CURRENT_STEP=""
    [[ "${DRY_RUN}" == "true" ]] || _mv_state_write "${token}"
}

_mv_run_pipeline() {
    local resuming=false
    [[ "${1:-}" == "--resume" ]] && resuming=true

    if [[ "${resuming}" == "true" ]]; then
        [[ -f "${_MV_STATE_FILE}" ]] || {
            log_error "No state file found. Cannot resume."
            log_error "Run: sudo utilities/setup-storage.sh migrate run ..."
            exit 1
        }
        local _resume_cli_force_format="${_MV_FORCE_FORMAT}"
        _MV_SOURCE="$(_mv_state_read MV_SOURCE)"
        _MV_TARGET="$(_mv_state_read MV_TARGET)"
        _MV_DEVICE="$(_mv_state_read MV_DEVICE)"
        [[ "${_MV_DEVICE}" == "none" ]] && _MV_DEVICE=""
        _MV_SKIP_STACK_STOP="$(_mv_state_read MV_SKIP_STACK_STOP)"
        _MV_DELETE_SOURCE="$(_mv_state_read MV_DELETE_SOURCE)"
        local _saved_force_format
        _saved_force_format="$(_mv_state_read MV_FORCE_FORMAT)"

        # Preserve a prior force-format authorization, but also allow a resume-time
        # --force-format to upgrade an older/incomplete state that saved false.
        if [[ "${_saved_force_format}" == "true" || "${_resume_cli_force_format}" == "true" ]]; then
            _MV_FORCE_FORMAT=true
            [[ "${DRY_RUN}" == "true" ]] || _mv_state_write MV_FORCE_FORMAT true
        else
            _MV_FORCE_FORMAT=false
        fi
        # Always restore direction from state — never require the operator to re-specify.
        # Default to boot-to-block for backwards compatibility with pre-direction state files.
        local _saved_direction
        _saved_direction="$(_mv_state_read MV_DIRECTION)"
        _MV_DIRECTION="${_saved_direction:-boot-to-block}"
        log_info "Resuming migration: ${_MV_SOURCE} → ${_MV_TARGET} (direction: ${_MV_DIRECTION})"

        log_info "Re-validating prerequisites for resume..."
        local _resume_ok=true
        if [[ ! -d "${_MV_SOURCE}" ]]; then
            if _mv_state_has STEP_SOURCE_RENAMED_DONE; then
                log_info "Resume: source was renamed in step 6 — original path absence is expected."
            else
                log_error "Resume: source directory no longer exists: ${_MV_SOURCE}"
                _resume_ok=false
            fi
        fi
        if [[ -n "${_MV_DEVICE}" ]]; then
            if [[ "${_MV_DIRECTION}" == "boot-to-block" ]]; then
                if _mv_state_has STEP_FORMAT_DONE; then
                    if ! mountpoint -q "${_MV_TARGET}" 2>/dev/null; then
                        log_error "Resume: saved target mount point is not mounted: ${_MV_TARGET}"
                        log_error "Refusing to discover or rewrite MV_TARGET from marker filenames."
                        log_error "Remount the expected target first, then re-run resume:"
                        log_error "  sudo mount ${_MV_TARGET}"
                        log_error "If the saved target path is wrong, inspect and edit ${_MV_STATE_FILE} explicitly before resuming."
                        _resume_ok=false
                    elif ! storage_validate_volume_identity "${_MV_TARGET}" "${_MV_DEVICE}"; then
                        log_error "Resume: saved target filesystem identity is invalid: ${_MV_TARGET}"
                        log_error "Refusing to continue onto a changed, copied, or unproven target filesystem."
                        _resume_ok=false
                    else
                        log_info "Resume: saved target filesystem identity validated."
                    fi
                elif mountpoint -q "${_MV_TARGET}" 2>/dev/null; then
                    if ! storage_validate_volume_identity "${_MV_TARGET}" "${_MV_DEVICE}"; then
                        log_error "Resume: target is already mounted before the format step, but its filesystem identity is invalid."
                        log_error "Repair/adopt only after proving the disk before resuming."
                        _resume_ok=false
                    else
                        log_info "Resume: pre-existing mounted target filesystem identity validated."
                    fi
                else
                    log_info "Resume: target mount is not active yet because the format/mount step is still pending."
                    log_info "Resume will continue with the saved target and device; MV_TARGET will not be rewritten."
                fi
            elif [[ "${_MV_DIRECTION}" == "block-to-boot" ]]; then
                if ! mountpoint -q "${_MV_SOURCE}" 2>/dev/null; then
                    log_error "Resume: block-to-boot source is no longer mounted: ${_MV_SOURCE}"
                    log_error "Remount the expected source volume before resuming."
                    _resume_ok=false
                elif ! storage_validate_volume_identity "${_MV_SOURCE}" "${_MV_DEVICE}"; then
                    log_error "Resume: block-to-boot source filesystem identity is invalid: ${_MV_SOURCE}"
                    log_error "Refusing to continue from a changed, copied, or unproven source filesystem."
                    _resume_ok=false
                else
                    log_info "Resume: block-to-boot source filesystem identity validated."
                fi

                # Target is a directory on the boot disk, not a mountpoint. A missing
                # target before rsync is recoverable; rsync will create/populate it.
                if [[ ! -d "${_MV_TARGET}" ]]; then
                    log_warn "Resume (block-to-boot): target directory does not exist: ${_MV_TARGET}"
                    log_warn "It will be created when rsync runs. This is safe to continue."
                else
                    local _tgt_count
                    _tgt_count="$(find "${_MV_TARGET}" -maxdepth 1 -mindepth 1 2>/dev/null | wc -l | tr -d ' ')"
                    log_info "Resume (block-to-boot): target directory exists with ${_tgt_count} item(s) — continuing."
                fi
            fi
        fi
        if [[ ! -f "${PROJECT_ROOT}/docker-compose.yml" ]]; then
            log_error "Resume: docker-compose.yml not found: ${PROJECT_ROOT}/docker-compose.yml"
            _resume_ok=false
        fi
        [[ "${_resume_ok}" == "true" ]] || {
            log_error "Resume validation failed. Fix the above issues and retry."
            return 1
        }
        log_info "Resume validation passed."
    fi

    local -a _pipeline_steps=(
        "STEP_VALIDATE_DONE:_mv_step_validate"
        "STEP_BACKUP_DONE:_mv_step_backup_prompt"
        "STEP_STOP_DONE:_mv_step_stop"
        "STEP_FORMAT_DONE:_mv_step_format"
        "STEP_RSYNC_DONE:_mv_step_rsync"
        "STEP_VERIFY_DONE:_mv_step_verify"
        "STEP_SOURCE_RENAMED_DONE:_mv_step_rename_source"
        "STEP_SOURCE_DELETED_DONE:_mv_step_delete_source"
        "STEP_ENV_UPDATED_DONE:_mv_step_update_env"
        "STEP_RUNTIME_ENV_SYNCED_DONE:_mv_step_sync_runtime_env"
        "STEP_DROPIN_UPDATED_DONE:_mv_step_update_dropin"
        "STEP_MOUNT_GUARD_DONE:_mv_step_mount_guard"
        "STEP_START_DONE:_mv_step_start"
        "STEP_HEALTHCHECK_DONE:_mv_step_healthcheck"
    )

    local _step _token _fn
    for _step in "${_pipeline_steps[@]}"; do
        _token="${_step%%:*}"
        _fn="${_step##*:}"
        case "${_token}" in
            STEP_SOURCE_DELETED_DONE)
                [[ "${_MV_DELETE_SOURCE}" == "true" ]] || continue
                ;;
        esac
        _mv_run_step "${_token}" "${_fn}"
    done
}

migrate_mode_main() {
    _MV_START_TIME="${SECONDS}"

    # On resume, restore the original run's log file path and run timestamp
    # from state before opening the log, so resume output appends to the same
    # log file and .env backup filenames match the original run.
    if [[ "${_MV_SUBCOMMAND}" == "resume" && -f "${_MV_STATE_FILE}" ]]; then
        local _saved_log _saved_ts
        _saved_log="$(_mv_state_read MV_LOG_FILE)"
        _saved_ts="$(_mv_state_read MV_START_TS)"
        [[ -n "${_saved_log}" ]] && _MV_LOG_FILE="${_saved_log}"
        [[ -n "${_saved_ts}" ]] && _MV_RUN_TIMESTAMP="$(date -d "@${_saved_ts}" +%Y%m%d_%H%M%S 2>/dev/null || echo "${_MV_RUN_TIMESTAMP}")"
    fi

    _mv_open_log

    trap '_mv_on_err $? $LINENO' ERR
    trap '_ss_cleanup; _mv_cleanup' EXIT

    _mv_acquire_lock

    case "${_MV_SUBCOMMAND}" in
        run)
            _mv_select_device
            _mv_prompt_target
            _mv_print_preflight_summary
            _mv_run_pipeline
            ;;
        resume)
            _mv_run_pipeline --resume
            ;;
        status)
            _mv_print_status
            ;;
        abort)
            _mv_do_abort
            ;;
        verify)
            if [[ -f "${_MV_STATE_FILE}" ]]; then
                local _sv _tv
                _sv="$(_mv_state_read MV_SOURCE)"
                _tv="$(_mv_state_read MV_TARGET)"
                if [[ -n "${_sv}" && -n "${_tv}" ]]; then
                    _MV_SOURCE="${_sv}"
                    _MV_TARGET="${_tv}"
                    log_info "verify: using paths from state file — source=${_MV_SOURCE} target=${_MV_TARGET}"
                fi
                # After step 6 (rename_source) the original source path no longer
                # exists. Discover the renamed directory and use it for the
                # byte-count comparison so verify works after a complete migration.
                if _mv_state_has STEP_SOURCE_RENAMED_DONE && [[ ! -d "${_MV_SOURCE}" ]]; then
                    local _renamed_src="" _cand _cand_ts _newest_ts=0
                    for _cand in "${_MV_SOURCE}.pre-migration."*/; do
                        [[ -d "${_cand}" ]] || continue
                        _cand_ts="$(stat -c '%Y' "${_cand}" 2>/dev/null || echo 0)"
                        if (( _cand_ts > _newest_ts )); then
                            _newest_ts="${_cand_ts}"
                            _renamed_src="${_cand%/}"
                        fi
                    done
                    if [[ -n "${_renamed_src}" ]]; then
                        log_info "verify: source was renamed (step 6) — comparing renamed source: ${_renamed_src}"
                        _MV_SOURCE="${_renamed_src}"
                    else
                        log_error "verify: STEP_SOURCE_RENAMED_DONE is set but no renamed source found matching '${_MV_SOURCE}.pre-migration.*'"
                        log_error "The renamed source may have been deleted. Cannot run byte-count comparison."
                        exit 1
                    fi
                fi
            fi
            _mv_step_verify
            ;;
        *)
            _mv_usage
            exit 1
            ;;
    esac
}
