# DDClient configuration for Cloudflare using Docker secrets
daemon=300
ssl=yes
use=web, web=https://checkip.amazonaws.com

protocol=cloudflare
zone=[DOMAIN]
ttl=1
login=token
password=REPLACE_ME
[FQDN DOMAIN]

