name: Regular health publisher probe

on:
  pull_request:
    branches: [delta]

permissions:
  contents: read

jobs:
  probe:
    runs-on: ubuntu-latest
    steps:
      - run: echo regular-health-publisher-probe
